version: '3'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    build: docker/openvpn
    container_name: openvpn
    ports:
      # openvpn
      - "1194:1194/udp"
      # nodered web
      - "1880:1880"
      # mqtt
      - "1883:1883"
      # home-assistant web
      - "8123:8123"
      # mqtt websocket
      - "9001:9001"
    volumes:
      - ./data/openvpn:/etc/openvpn
    restart: always
  broker:
    build: docker/mosquitto
    restart: always
    network_mode: service:openvpn
  nodered:
    build: docker/nodered
    volumes:
      - ./data/nodered:/data
    restart: always
    network_mode: service:openvpn
  ha:
    build: docker/homeassistant
    volumes:
      - ./data/home-assistant:/config
    environment:
      - TZ=Europe/Sofia
    restart: always
    network_mode: service:openvpn
