version: '3'
services:
  broker:
    image: eclipse-mosquitto
    ports:
    - "1883:1883"
    - "9001:9001"
  nodered:
    build: nodered
    ports:
    - "1880:1880"
    links:
    - broker
    volumes:
    - ./data/nodered:/data
