version: '3.8'
services:

  ingress:
    build: docker/nginx
    depends_on:
      - ingressgen
    restart: unless-stopped
    container_name: $INGRESS_NAME
    networks:
      ingress:
      dmz:
        ipv4_address: $INGRESS_ADDRESS
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${INGRESS_DATA_PATH}:/etc/nginx/conf.d:ro

  ingressgen:
    build: docker/dockergen
    restart: unless-stopped
    command: -notify-sighup $INGRESS_NAME -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    network_mode: none
    security_opt:
      - no-new-privileges:true
    configs:
      - source: ingressgen_template_nginx
        target: /etc/docker-gen/templates/nginx.tmpl
    environment:
      - TARGET_CONTAINER=$INGRESS_NAME
    volumes:
      - ${INGRESS_DATA_PATH}:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # fallback in case configs are not supported
      - ${INGRESSGEN_TEMPLATE_NGINX_FILE}:/etc/docker-gen/templates/nginx.tmpl:ro

  vpn:
    build: docker/wireguard
    restart: unless-stopped
    networks:
      - dmz
      - test-internal
      - test-internal2
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    configs:
      - source: vpn_template_peer
        target: /config/templates/peer.conf
      - source: vpn_template_server
        target: /config/templates/server.conf
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Sofia
      - SERVERURL=$VPN_PUBLIC_URL
      - SERVERPORT=$VPN_PUBLIC_PORT
      - PEERS=$VPN_PEERS
      - PEERDNS=auto
      - INTERNAL_SUBNET=$VPN_SUBNET
      - ALLOWEDIPS=$INGRESS_SUBNET
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /lib/modules:/lib/modules
      - ${VPN_DATA_PATH}:/config
      - ${VPN_TEMPLATE_PEER_FILE}:/config/templates/peer.conf:ro
      - ${VPN_TEMPLATE_SERVER_FILE}:/config/templates/server.conf:ro
    ports:
      - "${VPN_PUBLIC_PORT}:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

  broker:
    build: docker/mosquitto
    restart: unless-stopped
    networks:
      - automation
      - dmz
    security_opt:
      - no-new-privileges:true
    ports:
      - "1883:1883"

  nodered:
    build: docker/nodered
    depends_on:
      - broker
    restart: unless-stopped
    networks:
      - automation
      - ingress
      # needed to connect to broadcom rm+ pro ir remote
      - egress
    security_opt:
      - no-new-privileges:true
    configs:
      - source: nodered_flows
        target: /data/flows.json
      - source: nodered_package
        target: /data/package.json
      - source: nodered_settings
        target: /data/settings.js
    secrets:
      - nodered_credentials_key
    environment:
      - CREDENTIALS_KEY_FILE=/run/secrets/nodered_credentials_key
      - VIRTUAL_HOST=${NODERED_DOMAIN}
      - VIRTUAL_PORT=1880
    volumes:
      - ${NODERED_DATA}:/data
      - ${NODERED_CONFIG_FLOWS_FILE}:/data/flows.json:ro
      - ${NODERED_CONFIG_PACKAGE_FILE}:/data/package.json:ro
      - ${NODERED_CONFIG_SETTINGS_FILE}:/data/settings.js:ro

  ha:
    build: docker/homeassistant
    depends_on:
      - broker
    restart: unless-stopped
    networks:
      - automation
      - ingress
      - egress
    security_opt:
      - no-new-privileges:true
    configs:
      - source: homeassistant_configuration
        target: /config/configuration.yaml
      - source: homeassistant_automations
        target: /config/configuration/automations.yaml
      - source: homeassistant_customize
        target: /config/configuration/customize.yaml
      - source: homeassistant_groups
        target: /config/configuration/groups.yaml
      - source: homeassistant_scenes
        target: /config/configuration/scenes.yaml
      - source: homeassistant_scripts
        target: /config/configuration/scripts.yaml
    environment:
      - TZ=Europe/Sofia
      - VIRTUAL_HOST=${HOMEASSISTANT_DOMAIN}
      - VIRTUAL_PORT=8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOMEASSISTANT_DATA_PATH}:/config
      - ${HOMEASSISTANT_CONFIG_CONFIGURATION_FILE}:/config/configuration.yaml:ro
      - ${HOMEASSISTANT_CONFIG_AUTOMATIONS_FILE}:/config/configuration/automations.yaml:ro
      - ${HOMEASSISTANT_CONFIG_CUSTOMIZE_FILE}:/config/configuration/customize.yaml:ro
      - ${HOMEASSISTANT_CONFIG_GROUPS_FILE}:/config/configuration/groups.yaml:ro
      - ${HOMEASSISTANT_CONFIG_SCENES_FILE}:/config/configuration/scenes.yaml:ro
      - ${HOMEASSISTANT_CONFIG_SCRIPTS_FILE}:/config/configuration/scripts.yaml:ro

  mongo:
    build: docker/mongo
    restart: unless-stopped
    networks:
      - automation
    security_opt:
      - no-new-privileges:true
    secrets:
      - mongo_root_username
      - mongo_root_password
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_root_password
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - ${MONGO_DATA_PATH}:/data
#    user: ${PUID}:${PGID}

  mongo-express:
    build: docker/mongo-express
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - automation
      - ingress
    security_opt:
      - no-new-privileges:true
    secrets:
      - mongo_root_username
      - mongo_root_password
      - mongo_express_username
      - mongo_express_password
    environment:
      - TZ=Europe/Sofia
      - VIRTUAL_HOST=${MONGO_EXPRESS_DOMAIN}
      - VIRTUAL_PORT=8081
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME_FILE=/run/secrets/mongo_root_username
      - ME_CONFIG_MONGODB_ADMINPASSWORD_FILE=/run/secrets/mongo_root_password
      - ME_CONFIG_BASICAUTH_USERNAME_FILE=/run/secrets/mongo_express_username
      - ME_CONFIG_BASICAUTH_PASSWORD_FILE=/run/secrets/mongo_express_password
    volumes:
      - /etc/localtime:/etc/localtime:ro

  main-power:
    build: docker/modbus-serial
    restart: unless-stopped
    privileged: true
    networks:
      - automation
    environment:
      - DATABASE=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/power?authSource=admin
      - COLLECTION=main
      - CONFIG=/etc/config.js
      - BROKER=mqtt://broker
      - TOPIC=/modbus/main/{name}/reading
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./config/modbus-serial/main.config.js:/etc/config.js:ro

  secondary-power:
    build: docker/modbus-serial
    restart: unless-stopped
    privileged: true
    networks:
      - automation
    environment:
      - DATABASE=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/power?authSource=admin
      - COLLECTION=secondary
      - CONFIG=/etc/config.js
      - BROKER=mqtt://broker
      - TOPIC=/modbus/secondary/{name}/reading
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./config/modbus-serial/secondary.config.js:/etc/config.js:ro

  influxdb:
    build: docker/influxdb
    restart: unless-stopped
    networks:
      - automation
    environment:
      - TZ=Europe/Sofia
      - INFLUXDB_DB=${INFLUX_DATABASE}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - INFLUXDB_READ_USER=reader
      - INFLUXDB_READ_USER_PASSWORD=${INFLUXDB_READ_USER_PASSWORD}
      - INFLUXDB_WRITE_USER=writer
      - INFLUXDB_WRITE_USER_PASSWORD=${INFLUXDB_WRITE_USER_PASSWORD}
    volumes:
      - ./config/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./config/influxdb/init:/docker-entrypoint-initdb.d:ro
      - ./data/influxdb:/var/lib/influxdb
      - /etc/localtime:/etc/localtime:ro

  grafana:
    build: docker/grafana
    restart: unless-stopped
    networks:
      - automation
      - ingress
    environment:
      - TZ=Europe/Sofia
      - VIRTUAL_HOST=grafana.${DOMAIN}
      - VIRTUAL_PORT=3000
      - INFLUXDB_DATABASE=${INFLUX_DATABASE}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_READ_USER_PASSWORD}
    volumes:
      - ./config/grafana/config.ini:/etc/grafana/grafana.ini:ro
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./data/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    user: ${PUID}:${PGID}

# WIP - records mqtt in mongo
#  mqtt-mongo-primary:
#    build: docker/mqtt-mongo
#    restart: unless-stopped
#    networks:
#      - automation
#      - egress
#    environment:
#      - DATABASE=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/power?authSource=admin
#      - COLLECTION=primary
#      - BROKER=mqtt://broker
#      - TOPIC=/modbus/main/+/reading
#      - MQTT_CLIENT_ID=mqtt-mongo-primary

  mqtt-influx-primary:
    build: docker/mqtt-influx
    restart: unless-stopped
    networks:
      - automation
      - egress
    environment:
      - BROKER=mqtt://broker
      - TOPIC=/modbus/main/+/+
      - MQTT_CLIENT_ID=mqtt-influx-primary
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_USERNAME=writer
      - INFLUX_PASSWORD=${INFLUXDB_WRITE_USER_PASSWORD}
      - INFLUX_DATABASE=${INFLUX_DATABASE}
      - TAGS={"bus":"primary"}

  mqtt-influx-secondary:
    build: docker/mqtt-influx
    restart: unless-stopped
    networks:
      - automation
      - egress
    environment:
      - BROKER=mqtt://broker
      - TOPIC=/modbus/secondary/+/+
      - MQTT_CLIENT_ID=mqtt-influx-secondary
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_USERNAME=writer
      - INFLUX_PASSWORD=${INFLUXDB_WRITE_USER_PASSWORD}
      - INFLUX_DATABASE=${INFLUX_DATABASE}
      - TAGS={"bus":"secondary"}

  # Manualy run with
  # dc run historian-primary node index.js
  historian-primary:
    build: docker/historian
    restart: 'no'
    networks:
      - automation
      - egress
    environment:
      - BROKER=mqtt://broker
      - TOPIC=/modbus/main/{device}/history
      - MQTT_CLIENT_ID=historian-primary
      - DATABASE=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/power?authSource=admin
      - COLLECTION=main

  # Manualy run with
  # dc run historian-secondary node index.js
  historian-secondary:
    build: docker/historian
    restart: 'no'
    networks:
      - automation
      - egress
    environment:
      - BROKER=mqtt://broker
      - TOPIC=/modbus/secondary/{device}/history
      - MQTT_CLIENT_ID=historian-secondary
      - DATABASE=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/power?authSource=admin
      - COLLECTION=secondary

networks:
  # internal for the automation services - mqtt, node red, ah
  automation:
    internal: true
  # ingress proxy and exposed services
  ingress:
    internal: true
  # egress for containers needing access to external networks
  egress:
  # vpn, proxy
  dmz:
    ipam:
      config:
        - subnet: $INGRESS_SUBNET
  # internal networks for testing vpn access
  test-internal:
    internal: true
  test-internal2:
    internal: true

configs:
  ingressgen_template_nginx:
    file: ${INGRESSGEN_TEMPLATE_NGINX_FILE}
  vpn_template_peer:
    file: ${VPN_TEMPLATE_PEER_FILE}
  vpn_template_server:
    file: ${VPN_TEMPLATE_SERVER_FILE}
  nodered_flows:
    file: ${NODERED_CONFIG_FLOWS_FILE}
  nodered_package:
    file: ${NODERED_CONFIG_PACKAGE_FILE}
  nodered_settings:
    file: ${NODERED_CONFIG_SETTINGS_FILE}

secrets:
  mongo_express_password:
    file: ${MONGO_EXPRESS_SECRET_PASSWORD_FILE}
  mongo_express_username:
    file: ${MONGO_EXPRESS_SECRET_USERNAME_FILE}
  mongo_root_password:
    file: ${MONGO_SECRET_ROOT_PASSWORD_FILE}
  mongo_root_username:
    file: ${MONGO_SECRET_ROOT_USERNAME_FILE}
  nodered_credentials_key:
    file: ${NODERED_SECRET_CREDENTIALS_KEY_FILE}
