{
 "title": "Heatpump",
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Control",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "monitoring2",
     "query": "SELECT mean(\"targetTemp\") AS \"target\", mean(\"virtualTemp\") AS \"current\", mean(\"targetTemp\") - mean(\"pg2.hysteresis\") AS \"start\", mean(\"targetTemp\") + mean(\"pg2.offset\") AS \"stop\" FROM \"monitoring2\" WHERE (\"device.name\" = 'heatpump-ctrl') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "targetTemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "target" ], "type": "alias" }
      ],
      [
       { "params": [ "currentTemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "current" ], "type": "alias" }
      ],
      [
       { "params": [ "targetTemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "- 1.8" ], "type": "math" },
       { "params": [ "start" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device.name", "operator": "=", "value": "heatpump-ctrl" }
     ]
    },
    {
     "alias": "state.$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "monitoring2",
     "query": "SELECT\n  (max(\"inputs\"::integer) & 4) / 4 AS \"COMP\",\n  (max(\"inputs\"::integer) & 8) / 8 AS \"DEF\"\nFROM \"monitoring2\"\nWHERE \"device.name\" = 'heatpump-ctrl' AND $timeFilter\nGROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "inputs" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "& 4" ], "type": "math" },
       { "params": [ "target" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device.name", "operator": "=", "value": "heatpump-ctrl" }
     ]
    }
   ]
  },
  {
   "title": "COP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "($output * (7 + $bedroom*2 + $boris*2 + $gergana*2 + $martin*2) * 60 * 4184 / 3600 / $input) / $state",
     "type": "math"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "suffix: W" } },
   "targets": [
    { "expression": "$A+$B+$C", "type": "math" }
   ]
  },
  {
   "title": "Measured",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "monitoring2",
     "select": [
      [
       { "params": [ "s1Temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "internal.in" ], "type": "alias" }
      ],
      [
       { "params": [ "s3Temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "internal.out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device.name", "operator": "=", "value": "heatpump-ctrl" }
     ]
    },
    {
     "alias": "state.$col",
     "query": "SELECT\n  (max(\"inputs\"::integer) & 4) / 4 AS \"COMP\"\nFROM \"monitoring2\"\nWHERE \"device.name\" = 'heatpump-ctrl' AND $timeFilter\nGROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "AC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "min A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "device.name", "operator": "=", "value": "heat_pump" },
      { "condition": "AND", "key": "phase", "operator": "=", "value": "A" }
     ]
    },
    {
     "alias": "max A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device.name", "operator": "=", "value": "heat_pump" },
      { "condition": "AND", "key": "phase", "operator": "=", "value": "A" }
     ]
    },
    {
     "alias": "min B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "device.name", "operator": "=", "value": "heat_pump" },
      { "condition": "AND", "key": "phase", "operator": "=", "value": "B" }
     ]
    },
    {
     "alias": "max B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device.name", "operator": "=", "value": "heat_pump" },
      { "condition": "AND", "key": "phase", "operator": "=", "value": "B" }
     ]
    },
    {
     "alias": "min C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "device.name", "operator": "=", "value": "heat_pump" },
      { "condition": "AND", "key": "phase", "operator": "=", "value": "C" }
     ]
    },
    {
     "alias": "max C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_power",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "device.name", "operator": "=", "value": "heat_pump" },
      { "condition": "AND", "key": "phase", "operator": "=", "value": "C" }
     ]
    }
   ]
  },
  {
   "title": "Difference",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "alias": "diff",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "monitoring2",
     "query": "SELECT mean(\"s3Temp\") - mean(\"s1Temp\") FROM \"monitoring2\" WHERE (\"device.name\" = 'heatpump-ctrl') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "s1Temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "internal.in" ], "type": "alias" }
      ],
      [
       { "params": [ "s3Temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "internal.out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device.name", "operator": "=", "value": "heatpump-ctrl" }
     ]
    },
    {
     "alias": "state.$col",
     "query": "SELECT\n  (max(\"inputs\"::integer) & 4) / 4 AS \"COMP\"\nFROM \"monitoring2\"\nWHERE \"device.name\" = 'heatpump-ctrl' AND $timeFilter\nGROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Output",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "monitoring2",
     "select": [
      [
       { "params": [ "s3Temp" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "internal.out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device.name", "operator": "=", "value": "heatpump-ctrl" }
     ]
    }
   ]
  },
  {
   "title": "External",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "monitoring2",
     "select": [
      [
       { "params": [ "s2Temp" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "external.out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device.name", "operator": "=", "value": "heatpump-ctrl" }
     ]
    }
   ]
  }
 ]
}