apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    url: http://influxdb:8086
    database: $INFLUXDB_DATABASE
    access: proxy
    user: reader
    password: $INFLUXDB_USER_PASSWORD
    jsonData:
      httpMode: GET
