# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

homeassistant:
  customize: !include configuration/customize.yaml

updater:
  reporting: no
  include_used_components: false

# Text to speech
tts:
  - platform: google_translate

group: !include configuration/groups.yaml
automation: !include configuration/automations.yaml
script: !include configuration/scripts.yaml
scene: !include configuration/scenes.yaml

mqtt:
  broker: broker
  port: 1883
  client_id: home-assistant

light:
  - platform: mqtt
    name: "Баня 1 (1100)"
    command_topic: "/homy/ard1/output"
    payload_on: '{"pin":19,"value":1}'
    payload_off: '{"pin":19,"value":0}'

  - platform: mqtt
    name: "Офис (1200)"
    command_topic: "/homy/ard1/output"
    payload_on: '{"pin":20,"value":1}'
    payload_off: '{"pin":20,"value":0}'

  - platform: mqtt
    name: "Спалня лява нощна лампа (2528)"
    command_topic: "/homy/ard1/output"
    payload_on: '{"pin":21,"value":1}'
    payload_off: '{"pin":21,"value":0}'

  - platform: mqtt
    name: "Антре"
    command_topic: "/homy/ard1/output"
    payload_on: '{"pin":15,"value":1}'
    payload_off: '{"pin":15,"value":0}'

  - platform: mqtt
    name: "Коридор 2"
    command_topic: "/homy/ard1/output"
    payload_on: '{"pin":66,"value":"1"}'
    payload_off: '{"pin":66,"value":"0"}'

  - platform: mqtt
    name: "Кухня"
    command_topic: "/homy/ard1/output"
    payload_on: '{"pin":67,"value":"1"}'
    payload_off: '{"pin":67,"value":"0"}'

  - platform: mqtt
    name: "Коридор 1"
    command_topic: "/homy/ard1/output"
    payload_on: '{"pin":68,"value":"1"}'
    payload_off: '{"pin":68,"value":"0"}'

  - platform: mqtt
    name: "Хол"
    command_topic: "/homy/ard1/output"
    payload_on: '{"pin":69,"value":"1"}'
    payload_off: '{"pin":69,"value":"0"}'

  - platform: mqtt
    name: "Веранда"
    command_topic: "/homy/ard1/output"
    payload_on: '{"pin":62,"value":1}'
    payload_off: '{"pin":62,"value":0}'

  - platform: mqtt
    name: "Мокро"
    command_topic: "/homy/ard1/output"
    payload_on: '{"pin":65,"value":1}'
    payload_off: '{"pin":65,"value":0}'

switch:
  - platform: broadlink
    mac: B4:43:0D:B6:02:E2
    switches:
      - name: living_tv
        command_on: JgCMAJOSEzYTNxI3EhISEhMSFBAUERM2EjcUNRISExMSERMSFBATEhM4ERMSERMTERMSEhISEzYTEhM2EzYSNxQ2EjYTNxIABf2UkhE3FDUTNxIRFRATEhMRExETNxQ1EzcRExITERMSEhISExMSNhYOExMVDhMSExISEhM3ExETNhU0EzcRNxM2EzcTAA0FAAAAAAAAAAAAAAAA
        command_off: JgCQAJOSEjcSNxM2ExITERQQExISFBI2EzYSNxISExISEhMTERMSEhM3ExETERQRFg4WDxMRFDYSEhI4ETcTNxI2EzYTNhMABf2TkxI2EzYUNhISEhITExQQEhISNxM2EzcRExISExEUEhMQExMRNxQQExMSEhISFRAUEBM2ExISNxM2FDUTNxM1EzcTAAcoCwANBQAAAAAAAAAA
      - name: living_tv_vol_p
        command_on: JgDSAJKSEzcRNxM3EhEUEhISEhITEhQ1EjgSNhQREhMSERQRExMRNxM2EjcTERMSEhMTERISFBEUEBMTEzUSOBI2EzYUNRMABf2VkRE3FDUTNxESExMSExIRExMRNxI3EzYSEhMSExEUERMRFTUSNxI3ExETEhQQFBIREhQRExEUERM2EzYTNxI2FDUTAAX9k5ITNhQ2EjYTExETExIRExISEzYSOBM2ExAUEhISEhIUERM2EzcSNxESExITEhMRExIUEBMSFBATNhM2EzcTNhI3EgANBQAAAAAAAA==
      - name: living_tv_vol_m
        command_on: JgDSAJOSEjgROBE3ExISExETExETERQ2EjcTNhQQExMREhQSEhETNhM2ExQRNhQRExISEhMSExISERM2ExITNxI2FDUTNhMABf2TkhI3EzcSNhMSFBESExMQExISNxM2EjcTERMSExETEhMREzcSNxISEzUUEhMRExISEhQRExITNxESEzYUNhM1FDYSAAX9k5ITNhM2EzcSExIRExITERMSEzYTNxM1ExITERYPEhMSEhM3ETgTERI4ERMSEhQQExITERMSEjcTEhI2FDUUNhI4EgANBQAAAAAAAA==
      - name: living_tv_mute
        command_on: JgBoAJOSEzYSNxM2FBESEhMSExEUERM2EjgSNxISEhMSEhISExIUNRI4ETgSNhMRFhESERQRExIREhMSEhITNhQ1FDUTOBEACvOUkRM4ETgSNxISERQRExISEhITNhM2EzcSEhMSEhInAA0F
      - name: living_tv_source
        command_on: JgDUAJOREzYTNhM2ExEVEBMRExMSExE3FDUSNxMSEhMSERQREhIUNxESFBATExISFBATEhMSEhISNxM2EzYSNxMjDgUUNhI3EgAF/JSSEjcSNxI3FBATEhQQExISEhM2EzYTOBETExETERMSEhMSNxMSERMSExISEhITERMSExEUNhM3EjYSOBE3EjcTNhIABf6UkRM2EjcUNRQSERMSEhMSEhISNxM2FDUTEhISExETExESFDUTEhQREhITERMSExISEhMTEjYTNhM2EzcSNhM2FDUUAA0FAAAAAA==
      - name: living_tv_ok
        command_on: JgCMAJWQEzYTNxM1FBESEhMSEhQRExI2EjcTNhQREhMSEhMRFBESExISFBESNhMTEjcTNRMSEzYSNxI3ExMTNhESFBAVNhEABf2TkhQ1EzYTNxITExATEhQSEhESOBI2FDUTEhMRFBESEhMSEhITEhMRFTQTEhM3EjYUEhE3EjcSNxQQEzcSEhMSEzYTAA0FAAAAAAAAAAAAAAAA
      - name: living_tv_exit
        command_on: JgDSAJOSEzYUNRM2ExITERMSEhMSEhI3EzcTNRQSERMSERMSExETOBMREjYTNhQSETcTExIREhQRNhQRFBESNxISFDUTNxIABf2UkhI2EzcSNhMSEhMSEhMRExMRNxM2EzYTEhMRExITERQRFDUTERU2EjUVEBM2FBETExESEzYSEhMSEzcTERQ1EjcSAAX9lZATOBE3EjcUEBMSFBATEhMTEjYTNhI3EhMSEhMRExMSERQ3EhEUNRI3ExISNxITEhIUEBM4ERITExE2ExITNhM2EwANBQAAAAAAAA==

