- name: Main current A
  device_class: current
  state_class: measurement
  unit_of_measurement: A
  state_topic: "/modbus/main/main/reading"
  value_template: "{{ value_json.ac | float(default=0) }}"

- name: Main current B
  device_class: current
  state_class: measurement
  unit_of_measurement: A
  state_topic: "/modbus/main/main/reading"
  value_template: "{{ value_json.bc | float(default=0) }}"

- name: Main current C
  device_class: current
  state_class: measurement
  unit_of_measurement: A
  state_topic: "/modbus/main/main/reading"
  value_template: "{{ value_json.cc | float(default=0) }}"

- name: Main power factor A
  device_class: power_factor
  state_class: measurement
  unit_of_measurement: '%'
  state_topic: "/modbus/main/main/reading"
  value_template: "{{ value_json.apf | float(default=0) }}"

- name: Main power factor B
  device_class: power_factor
  state_class: measurement
  unit_of_measurement: '%'
  state_topic: "/modbus/main/main/reading"
  value_template: "{{ value_json.bpf | float(default=0) }}"

- name: Main power factor C
  device_class: power_factor
  state_class: measurement
  unit_of_measurement: '%'
  state_topic: "/modbus/main/main/reading"
  value_template: "{{ value_json.cpf | float(default=0) }}"

- name: Main voltage A
  device_class: voltage
  state_class: measurement
  unit_of_measurement: V
  state_topic: "/modbus/main/main/reading"
  value_template: "{{ value_json.av | float(default=0) }}"

- name: Main voltage B
  device_class: voltage
  state_class: measurement
  unit_of_measurement: V
  state_topic: "/modbus/main/main/reading"
  value_template: "{{ value_json.bv | float(default=0) }}"

- name: Main voltage C
  device_class: voltage
  state_class: measurement
  unit_of_measurement: V
  state_topic: "/modbus/main/main/reading"
  value_template: "{{ value_json.cv | float(default=0) }}"

- name: Main frequency
  device_class: frequency
  state_class: measurement
  unit_of_measurement: Hz
  state_topic: "/modbus/main/main/reading"
  value_template: "{{ value_json.freq | float(default=0) }}"

- name: Main energy used
  state_topic: "/modbus/main/main/reading"
  value_template: "{{ value_json.total_import_kwh | float(default=0) }}"
  last_reset_value_template: "2023-10-15T70:00:00Z"
  <<: &common_used_energy
    device_class: energy
    state_class: total
    unit_of_measurement: kWh

- name: Main energy returned
  state_topic: "/modbus/main/main/reading"
  value_template: "{{ value_json.total_export_kwh | float(default=0) }}"
  last_reset_value_template: "2023-10-15T70:00:00Z"
  <<: &common_used_energy
    device_class: energy
    state_class: total
    unit_of_measurement: kWh

- name: Water pump energy used
  state_topic: "/modbus/secondary/water_pump/reading"
  value_template: "{{ value_json.tot_act | float(default=0) }}"
  <<: *common_used_energy

- name: Waste pump energy used
  state_topic: "/modbus/secondary/waste_pump/reading"
  value_template: "{{ value_json.tot_act | float(default=0) }}"
  <<: *common_used_energy

- name: Oven energy used
  state_topic: "/modbus/secondary/oven/reading"
  value_template: "{{ value_json.tot | float(default=0) }}"
  <<: *common_used_energy

- name: Stove energy used
  state_topic: "/modbus/secondary/stove/reading"
  value_template: "{{ value_json.tot | float(default=0) }}"
  <<: *common_used_energy

- name: Dishwasher energy used
  state_topic: "/modbus/secondary/dishwasher/reading"
  value_template: "{{ value_json.tot | float(default=0) }}"
  <<: *common_used_energy

- name: Kitchen energy used
  state_topic: "/modbus/secondary/kitchen/reading"
  value_template: "{{ value_json.tot | float(default=0) }}"
  <<: *common_used_energy

- name: Laundry energy used
  state_topic: "/modbus/secondary/laundry/reading"
  value_template: "{{ value_json.tot | float(default=0) }}"
  <<: *common_used_energy

- name: Boiler energy used
  state_topic: "/modbus/secondary/boiler/reading"
  value_template: "{{ value_json.tot | float(default=0) }}"
  <<: *common_used_energy

- name: Heat pump energy used
  state_topic: "/modbus/tetriary/heat_pump/reading"
  value_template: "{{ value_json.tot_act | float(default=0) }}"
  last_reset_value_template: "2023-10-15T70:00:00Z"
  <<: *common_used_energy

- name: Stabilizator energy used
  state_topic: "/modbus/monitoring2/stab-em/reading"
  value_template: "{{ value_json.totalActiveEnergy | float(default=0) }}"
  <<: *common_used_energy

- name: Microwave energy used
  state_topic: "/modbus/secondary/microwave/reading"
  value_template: "{{ value_json.tot | float(default=0) }}"
  <<: *common_used_energy
