version: 1
update_configs:
  # requires dependabot/dependabot-core#390
  # - package_manager: "docker"
  #   directory: "/"
  #   update_schedule: "daily"
  #   default_reviewers:
  #     - "groupsky"

  - package_manager: "docker"
    directory: "/docker/homeassistant"
    update_schedule: "daily"
    default_reviewers:
      - "groupsky"

  - package_manager: "docker"
    directory: "/docker/mosquitto"
    update_schedule: "daily"
    default_reviewers:
      - "groupsky"

  - package_manager: "docker"
    directory: "/docker/nodered"
    update_schedule: "daily"
    default_reviewers:
      - "groupsky"

  - package_manager: "docker"
    directory: "/docker/openvpn"
    update_schedule: "daily"
    default_reviewers:
      - "groupsky"
