- platform: mqtt
  name: Dishwasher
  state_topic: "/modbus/secondary/dishwasher/reading"
  value_template: "{{ 'ON' if value_json.p|float > 10 else 'OFF' }}"

- platform: mqtt
  name: Laundry
  state_topic: "/modbus/secondary/laundry/reading"
  value_template: "{{ 'ON' if value_json.p|float > 1 else 'OFF' }}"

- platform: mqtt
  name: Oven
  state_topic: "/modbus/secondary/oven/reading"
  value_template: "{{ 'ON' if value_json.p|float > 1 else 'OFF' }}"

- platform: mqtt
  name: Stove
  state_topic: "/modbus/secondary/stove/reading"
  value_template: "{{ 'ON' if value_json.p|float > 10 else 'OFF' }}"
