- platform: mqtt
  name: "Front door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'on' if value_json.inputs|bitwise_and(1) else 'off' }}"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Front side door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'on' if value_json.inputs|bitwise_and(2) else 'off' }}"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Living room window"
  device_class: "window"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'on' if value_json.inputs|bitwise_and(4) else 'off' }}"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Cabinet south window"
  device_class: "window"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'on' if value_json.inputs|bitwise_and(8) else 'off' }}"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Cabinet west window"
  device_class: "window"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'on' if value_json.inputs|bitwise_and(16) else 'off' }}"
  payload_on: "on"
  payload_off: "off"
