- platform: mqtt
  name: "Front door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(1) else 'ON' }}"

- platform: mqtt
  name: "Front side door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(2) else 'ON' }}"

- platform: mqtt
  name: "Living room window"
  device_class: "window"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(4) else 'ON' }}"

- platform: mqtt
  name: "Cabinet south window"
  device_class: "window"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(8) else 'ON' }}"

- platform: mqtt
  name: "Cabinet west window"
  device_class: "window"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(16) else 'ON' }}"

- platform: mqtt
  name: "Cabinet west window"
  device_class: "window"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(32) else 'ON' }}"

- platform: mqtt
  name: "Bath 1 Door"
  device_class: "lock"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(64) else 'ON' }}"

- platform: mqtt
  name: "Bath 1 Door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(128) else 'ON' }}"

- platform: mqtt
  name: "Cabinet Door"
  device_class: "lock"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(256) else 'ON' }}"

- platform: mqtt
  name: "Cabinet Door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(512) else 'ON' }}"

- platform: mqtt
  name: "Bath 2 Door"
  device_class: "lock"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(1024) else 'ON' }}"

- platform: mqtt
  name: "Bath 2 Door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(2048) else 'ON' }}"

- platform: mqtt
  name: "Bath 3 Door"
  device_class: "lock"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(4096) else 'ON' }}"

- platform: mqtt
  name: "Bath 3 Door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(8192) else 'ON' }}"

- platform: mqtt
  name: "Gery Door"
  device_class: "lock"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(16384) else 'ON' }}"

- platform: mqtt
  name: "Gery Door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(32768) else 'ON' }}"

- platform: mqtt
  name: "Bedroom Door"
  device_class: "lock"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(65536) else 'ON' }}"

- platform: mqtt
  name: "Bedroom Door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(131072) else 'ON' }}"

- platform: mqtt
  name: "Bobo Door"
  device_class: "lock"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(262144) else 'ON' }}"

- platform: mqtt
  name: "Bobo Door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(524288) else 'ON' }}"

- platform: mqtt
  name: "Bath 1"
  device_class: "window"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(1048576) else 'ON' }}"

- platform: mqtt
  name: "Marti Door"
  device_class: "lock"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(2097152) else 'ON' }}"

- platform: mqtt
  name: "Marti Door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(4194304) else 'ON' }}"

- platform: mqtt
  name: "Service Door"
  device_class: "lock"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(8388608) else 'ON' }}"

- platform: mqtt
  name: "Service Door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(16777216) else 'ON' }}"

- platform: mqtt
  name: Dishwasher
  state_topic: "/modbus/secondary/dishwasher/reading"
  value_template: "{{ 'ON' if value_json.p|float > 10 else 'OFF' }}"

- platform: mqtt
  name: Laundry
  state_topic: "/modbus/secondary/laundry/reading"
  value_template: "{{ 'ON' if value_json.p|float > 1 else 'OFF' }}"

- platform: mqtt
  name: Oven
  state_topic: "/modbus/secondary/oven/reading"
  value_template: "{{ 'ON' if value_json.p|float > 1 else 'OFF' }}"

- platform: mqtt
  name: Stove
  state_topic: "/modbus/secondary/stove/reading"
  value_template: "{{ 'ON' if value_json.p|float > 10 else 'OFF' }}"
