- platform: mqtt
  name: "Front door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'off' if value_json.inputs|bitwise_and(1) else 'on' }}"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Front side door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'off' if value_json.inputs|bitwise_and(2) else 'on' }}"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Living room window"
  device_class: "window"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'off' if value_json.inputs|bitwise_and(4) else 'on' }}"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Cabinet south window"
  device_class: "window"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'off' if value_json.inputs|bitwise_and(8) else 'on' }}"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Cabinet west window"
  device_class: "window"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'off' if value_json.inputs|bitwise_and(16) else 'on' }}"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Stove"
  icon: mdi:stove
  state_topic: "/modbus/secondary/stove/reading"
  value_template: "{{ 'on' if value_json.p > 35 else 'off' }}"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Oven"
  icon: mdi:stove
  state_topic: "/modbus/secondary/oven/reading"
  value_template: "{{ 'on' if value_json.p > 1 else 'off' }}"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Dishwasher"
  icon: mdi:dishwasher
  state_topic: "/modbus/secondary/dishwasher/reading"
  value_template: "{{ 'on' if value_json.p > 1 else 'off' }}"
  payload_on: "on"
  payload_off: "off"

- platform: mqtt
  name: "Laundry"
  icon: mdi:laundry
  state_topic: "/modbus/secondary/laundry/reading"
  value_template: "{{ 'on' if value_json.p > 1 else 'off' }}"
  payload_on: "on"
  payload_off: "off"
