- platform: mqtt
  name: "Front door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(1) else 'ON' }}"

- platform: mqtt
  name: "Front side door"
  device_class: "door"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(2) else 'ON' }}"

- platform: mqtt
  name: "Living room window"
  device_class: "window"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(4) else 'ON' }}"

- platform: mqtt
  name: "Cabinet south window"
  device_class: "window"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(8) else 'ON' }}"

- platform: mqtt
  name: "Cabinet west window"
  device_class: "window"
  state_topic: "/modbus/dry-switches/mbsl32di1/reading"
  value_template: "{{ 'OFF' if value_json.inputs|bitwise_and(16) else 'ON' }}"

- platform: mqtt
  name: dishwasher_electricity
  device_class: power
  state_topic: "/modbus/secondary/dishwasher/reading"
  value_template: "{{ 'ON' if value_json.p|float > 1 else 'OFF' }}"
#  json_attributes_topic: "/modbus/secondary/dishwasher/reading"
#  json_attributes_template: "{{ value_json | tojson }}"

- platform: mqtt
  name: laundry_electricity
  device_class: plug
  state_topic: "/modbus/secondary/laundry/reading"
  value_template: "{{ 'ON' if value_json.p|float > 1 else 'OFF' }}"
#  json_attributes_topic: "/modbus/secondary/laundry/reading"
#  json_attributes_template: "{{ value_json | tojson }}"

- platform: mqtt
  name: oven_electricity
  device_class: heat
  state_topic: "/modbus/secondary/oven/reading"
  value_template: "{{ 'ON' if value_json.p|float > 1 else 'OFF' }}"
#  json_attributes_topic: "/modbus/secondary/oven/reading"
#  json_attributes_template: "{{ value_json | tojson }}"

- platform: mqtt
  name: stove_electricity
  state_topic: "/modbus/secondary/stove/reading"
  value_template: "{{ 'ON' if value_json.p|float > 1 else 'OFF' }}"
#  json_attributes_topic: "/modbus/secondary/stove/reading"
#  json_attributes_template: "{{ value_json | tojson }}"
