- platform: mqtt
  name: Martin
  modes:
    - "off"
    - "heat"
    - "cool"
    - "fan_only"
  fan_modes:
    - "auto"
    - "low"
    - "medium"
    - "high"
  precision: 0.5
  temperature_unit: "C"
  temp_step: 0.5
  current_temperature_topic: /modbus/monitoring/thermostat-martin/reading
  fan_mode_state_topic: /modbus/monitoring/thermostat-martin/reading
  json_attributes_topic: /modbus/monitoring/thermostat-martin/reading
  mode_state_topic: /modbus/monitoring/thermostat-martin/reading
  temperature_state_topic: /modbus/monitoring/thermostat-martin/reading
  current_temperature_template: "{{ value_json.currentTemp|float }}"
  fan_mode_state_template: "{{ 'medium' if value_json.fanSetting == 'mid' else value_json.fanSetting }}"
  mode_state_template: >-
    {% if value_json.power == 'on' %}
      {{ 'off' if value_json.power == 'off' }}
      {{ 'cool' if value_json.mode == 'cooling' }}
      {{ 'heat' if value_json.mode == 'heating' }}
      {{ 'fan_only' if value_json.mode == 'ventilation' }}
    {% elif value_json.power == 'off' %}
      off
    {% endif %}
  temperature_state_template: "{{ value_json.currentTemp }}"
