switch.living_tv:
  friendly_name: 'Power'
  icon: mdi:power-standby

switch.living_tv_vol_p:
  friendly_name: 'Vol+'
  icon: mdi:volume-plus

switch.living_tv_vol_m:
  friendly_name: 'Vol-'
  icon: mdi:volume-minus

switch.living_tv_mute:
  friendly_name: 'Mute'
  icon: mdi:volume-off

switch.living_tv_source:
  friendly_name: 'Source'
  icon: mdi:video-switch-outline

switch.living_tv_ok:
  friendly_name: 'OK'
  icon: mdi:check

switch.living_tv_back:
  friendly_name: 'Return'
  icon: mdi:restore

switch.living_tv_exit:
  friendly_name: 'Exit'
  icon: mdi:exit-to-app

sensor.inverter_sun2000_accumulated_yield:
  friendly_name: Inverter

sensor.heat_pump_dds024mr_tot_act:
  friendly_name: Heat pump (after 2023-10-15)
sensor.heat_pump_energy_used:
  friendly_name: Heat pump (until 2023-10-15)

sensor.main_energy_sdm630_total_import_kwh:
  friendly_name: Import (after 2023-10-15)
sensor.main_energy_used:
  friendly_name: Import (until 2023-10-15)
sensor.main_energy_sdm630_total_export_kwh:
  friendly_name: Export (after 2023-10-15)
