switch.living_tv:
  friendly_name: 'Power'
  icon: mdi:power-standby

switch.living_tv_vol_p:
  friendly_name: 'Vol+'
  icon: mdi:volume-plus

switch.living_tv_vol_m:
  friendly_name: 'Vol-'
  icon: mdi:volume-minus

switch.living_tv_mute:
  friendly_name: 'Mute'
  icon: mdi:volume-off

switch.living_tv_source:
  friendly_name: 'Source'
  icon: mdi:video-switch-outline

switch.living_tv_ok:
  friendly_name: 'OK'
  icon: mdi:check

switch.living_tv_back:
  friendly_name: 'Return'
  icon: mdi:restore

switch.living_tv_exit:
  friendly_name: 'Exit'
  icon: mdi:exit-to-app

#sensor.stove_electricity:
#  friendly_name: 'Stove'
#  icon: mdi:stove
#
#sensor.oven_electricity:
#  friendly_name: 'Oven'
#  icon: mdi:stove
#
#sensor.dishwasher_electricity:
#  friendly_name: 'Dishwasher'
#  icon: mdi:dishwasher
#
#sensor.laundry_electricity:
#  friendly_name: 'Laundry'
#  icon: mdi:washing-machine
