- platform: mqtt
  name: "Антре"
  schema: template
  command_topic: "/homy/ard1/output"
  state_topic: "/homy/ard1/input"
  command_on_template: '{"pin": 15, "value": 1}'
  command_off_template: '{"pin": 15, "value": 0}'
  state_template: >-
    {% if value_json.p == 15 %}
      {{ 'on' if value_json.v == 0 }}
      {{ 'off' if value_json.v == 1 }}
    {% endif %}

- platform: mqtt
  name: "Баня 2"
  schema: template
  command_topic: "/homy/ard1/output"
  state_topic: "/homy/ard1/input"
  command_on_template: '{"pin": 16, "value": 1}'
  command_off_template: '{"pin": 16, "value": 0}'
  state_template: >-
    {% if value_json.p == 16 %}
      {{ 'on' if value_json.v == 0 }}
      {{ 'off' if value_json.v == 1 }}
    {% endif %}

- platform: mqtt
  name: "Спалня"
  schema: template
  command_topic: "/homy/ard1/output"
  state_topic: "/homy/ard1/input"
  command_on_template: '{"pin": 17, "value": 1}'
  command_off_template: '{"pin": 17, "value": 0}'
  state_template: >-
    {% if value_json.p == 17 %}
      {{ 'on' if value_json.v == 0 }}
      {{ 'off' if value_json.v == 1 }}
    {% endif %}

- platform: mqtt
  name: "Мартин"
  schema: template
  command_topic: "/homy/ard1/output"
  state_topic: "/homy/ard1/input"
  command_on_template: '{"pin": 18, "value": 1}'
  command_off_template: '{"pin": 18, "value": 0}'
  state_template: >-
    {% if value_json.p == 18 %}
      {{ 'on' if value_json.v == 0 }}
      {{ 'off' if value_json.v == 1 }}
    {% endif %}

- platform: mqtt
  name: "Баня 1 (1100)"
  schema: template
  command_topic: "/homy/ard1/output"
  state_topic: "/homy/ard1/input"
  command_on_template: '{"pin": 19, "value": 1}'
  command_off_template: '{"pin": 19, "value": 0}'
  state_template: >-
    {% if value_json.p == 19 %}
      {{ 'on' if value_json.v == 0 }}
      {{ 'off' if value_json.v == 1 }}
    {% endif %}

- platform: mqtt
  name: "Офис (1200)"
  schema: template
  command_topic: "/homy/ard1/output"
  state_topic: "/homy/ard1/input"
  command_on_template: '{"pin": 20, "value": 1}'
  command_off_template: '{"pin": 20, "value": 0}'
  state_template: >-
    {% if value_json.p == 20 %}
      {{ 'on' if value_json.v == 0 }}
      {{ 'off' if value_json.v == 1 }}
    {% endif %}

- platform: mqtt
  name: "Спалня лява нощна лампа (2528)"
  schema: template
  command_topic: "/homy/ard1/output"
  state_topic: "/homy/ard1/input"
  command_on_template: '{"pin": 21, "value": 1}'
  command_off_template: '{"pin": 21, "value": 0}'
  state_template: >-
    {% if value_json.p == 21 %}
      {{ 'on' if value_json.v == 0 }}
      {{ 'off' if value_json.v == 1 }}
    {% endif %}

- platform: mqtt
  name: "Веранда"
  schema: template
  command_topic: "/homy/ard1/output"
  state_topic: "/homy/ard1/input"
  command_on_template: '{"pin": 62, "value": 1}'
  command_off_template: '{"pin": 62, "value": 0}'
  state_template: >-
    {% if value_json.p == 62 %}
      {{ 'on' if value_json.v == 1 }}
      {{ 'off' if value_json.v == 0 }}
    {% endif %}

- platform: mqtt
  name: "Гергана"
  schema: template
  command_topic: "/homy/ard1/output"
  state_topic: "/homy/ard1/input"
  command_on_template: '{"pin": 63, "value": 1}'
  command_off_template: '{"pin": 63, "value": 0}'
  state_template: >-
    {% if value_json.p == 63 %}
      {{ 'on' if value_json.v == 1 }}
      {{ 'off' if value_json.v == 0 }}
    {% endif %}

- platform: mqtt
  name: "Борис"
  schema: template
  command_topic: "/homy/ard1/output"
  state_topic: "/homy/ard1/input"
  command_on_template: '{"pin": 64, "value": 1}'
  command_off_template: '{"pin": 64, "value": 0}'
  state_template: >-
    {% if value_json.p == 64 %}
      {{ 'on' if value_json.v == 1 }}
      {{ 'off' if value_json.v == 0 }}
    {% endif %}

- platform: mqtt
  name: "Мокро"
  schema: template
  command_topic: "/homy/ard1/output"
  state_topic: "/homy/ard1/input"
  command_on_template: '{"pin": 65, "value": 1}'
  command_off_template: '{"pin": 65, "value": 0}'
  state_template: >-
    {% if value_json.p == 65 %}
      {{ 'on' if value_json.v == 1 }}
      {{ 'off' if value_json.v == 0 }}
    {% endif %}

- platform: mqtt
  name: "Коридор 2"
  schema: template
  command_topic: "/homy/ard1/output"
  state_topic: "/homy/ard1/input"
  command_on_template: '{"pin": 66, "value": 1}'
  command_off_template: '{"pin": 66, "value": 0}'
  state_template: >-
    {% if value_json.p == 66 %}
      {{ 'on' if value_json.v == 1 }}
      {{ 'off' if value_json.v == 0 }}
    {% endif %}

- platform: mqtt
  name: "Кухня"
  schema: template
  command_topic: "/homy/ard1/output"
  state_topic: "/homy/ard1/input"
  command_on_template: '{"pin": 67, "value": 1}'
  command_off_template: '{"pin": 67, "value": 0}'
  state_template: >-
    {% if value_json.p == 67 %}
      {{ 'on' if value_json.v == 1 }}
      {{ 'off' if value_json.v == 0 }}
    {% endif %}

- platform: mqtt
  name: "Коридор 1"
  schema: template
  command_topic: "/homy/ard1/output"
  state_topic: "/homy/ard1/input"
  command_on_template: '{"pin": 68, "value": 1}'
  command_off_template: '{"pin": 68, "value": 0}'
  state_template: >-
    {% if value_json.p == 68 %}
      {{ 'on' if value_json.v == 1 }}
      {{ 'off' if value_json.v == 0 }}
    {% endif %}

- platform: mqtt
  name: "Хол"
  schema: template
  command_topic: "/homy/ard1/output"
  state_topic: "/homy/ard1/input"
  command_on_template: '{"pin": 69, "value": 1}'
  command_off_template: '{"pin": 69, "value": 0}'
  state_template: >-
    {% if value_json.p == 69 %}
      {{ 'on' if value_json.v == 1 }}
      {{ 'off' if value_json.v == 0 }}
    {% endif %}

- platform: mqtt
  name: "Външно"
  schema: template
  command_topic: "/modbus/dry-switches/relays00-15/write"
  state_topic: "/modbus/dry-switches/relays00-15/reading"
  command_on_template: '{"out15": true}'
  command_off_template: '{"out15": false}'
  state_template: {{ 'ON' if value_json.outputs|bitwise_and(2**15) else 'OFF' }}
