- platform: mqtt
  name: dishwasher_electricity
  state_topic: "/modbus/secondary/dishwasher/reading"
  value_template: "{{ 'on' if value_json.p > 1 else 'off' }}"
#  json_attributes_topic: "/modbus/secondary/dishwasher/reading"
#  json_attributes_template: "{{ value_json | tojson }}"

- platform: mqtt
  name: laundry_electricity
  state_topic: "/modbus/secondary/laundry/reading"
  value_template: "{{ 'on' if value_json.p > 1 else 'off' }}"

- platform: mqtt
  name: oven_electricity
  state_topic: "/modbus/secondary/oven/reading"
  value_template: "{{ 'on' if value_json.p > 1 else 'off' }}"

- platform: mqtt
  name: stove_electricity
  state_topic: "/modbus/secondary/stove/reading"
  value_template: "{{ 'on' if value_json.p > 1 else 'off' }}"

- platform: template
  sensors:
    oven_state:
      friendly_name: "Day/Night"
      value_template: >-
        {% if is_state('sensor.oven_electricity', 'on') %}
          On
        {% else %}
          Off
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.oven_electricity', 'on') %}
          mdi:stove
        {% endif %}
