#!/bin/bash
#
# Backup Script
#
# Creates a backup of all databases (InfluxDB, MongoDB, Home Assistant).
#

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BACKUP_REF_FILE="$PROJECT_DIR/.pre-upgrade-backup"

# Default values
BACKUP_NAME=""
STOP_SERVICES=false
SKIP_CONFIRM=false
QUIET=false

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS] [BACKUP_NAME]

Create a backup of all databases (InfluxDB, MongoDB, Home Assistant).

Arguments:
  BACKUP_NAME         Optional name for the backup (default: timestamp YYYY_MM_DD_HH_MM_SS)

Options:
  -h, --help          Show this help message and exit
  -s, --stop          Stop services before backup (recommended for consistency)
  -y, --yes           Skip confirmation prompt
  -q, --quiet         Suppress output except errors (for scripting)

Examples:
  $(basename "$0")                    # Create backup with timestamp name
  $(basename "$0") pre-upgrade        # Create backup named 'pre-upgrade'
  $(basename "$0") -s -y              # Stop services, no confirmation
  $(basename "$0") -q                 # Quiet mode for scripts

Notes:
  - Backups are stored in the backup volume mounted by volman
  - Use 'rollback.sh --list' or 'restore.sh --list' to see available backups
  - For consistent backups, use --stop to stop services first

EOF
    exit 0
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            usage
            ;;
        -s|--stop)
            STOP_SERVICES=true
            shift
            ;;
        -y|--yes)
            SKIP_CONFIRM=true
            shift
            ;;
        -q|--quiet)
            QUIET=true
            SKIP_CONFIRM=true
            shift
            ;;
        -*)
            echo "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
        *)
            BACKUP_NAME="$1"
            shift
            ;;
    esac
done

log() {
    if [ "$QUIET" = false ]; then
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
    fi
}

confirm() {
    if [ "$SKIP_CONFIRM" = true ]; then
        return 0
    fi

    local prompt="$1"
    echo ""
    read -r -p "$prompt [y/N] " response
    case "$response" in
        [yY][eE][sS]|[yY])
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

# Change to project directory
cd "$PROJECT_DIR"

if [ ! -f docker-compose.yml ]; then
    echo "ERROR: docker-compose.yml not found. Not in project root?" >&2
    exit 1
fi

# Show backup plan
if [ "$QUIET" = false ]; then
    echo ""
    echo "═══════════════════════════════════════════════════════════════"
    echo "                       BACKUP PLAN"
    echo "═══════════════════════════════════════════════════════════════"
    echo ""
    echo "  Backup name:     ${BACKUP_NAME:-<auto-generated timestamp>}"
    echo "  Stop services:   $STOP_SERVICES"
    echo ""
    echo "  This will backup:"
    echo "    - InfluxDB data"
    echo "    - MongoDB data"
    echo "    - Home Assistant configuration"
    echo ""
    echo "═══════════════════════════════════════════════════════════════"
fi

if ! confirm "Proceed with backup?"; then
    log "Backup cancelled by user"
    exit 0
fi

# Stop services if requested
SERVICES_STOPPED=false
if [ "$STOP_SERVICES" = true ]; then
    log "Stopping services for consistent backup..."
    docker compose down
    SERVICES_STOPPED=true
fi

# Run backup
log "Creating backup..."
BACKUP_CMD="docker compose run --rm volman backup"
if [ -n "$BACKUP_NAME" ]; then
    BACKUP_CMD="$BACKUP_CMD $BACKUP_NAME"
fi

BACKUP_OUTPUT=$($BACKUP_CMD 2>&1) || {
    echo "ERROR: Backup failed" >&2
    echo "$BACKUP_OUTPUT" >&2
    # Restart services if we stopped them
    if [ "$SERVICES_STOPPED" = true ]; then
        log "Restarting services..."
        docker compose up -d
    fi
    exit 1
}

# Extract actual backup name from output
ACTUAL_BACKUP_NAME=$(echo "$BACKUP_OUTPUT" | grep -oP 'Creating backup \K[0-9_]+' || echo "$BACKUP_NAME")
if [ -z "$ACTUAL_BACKUP_NAME" ]; then
    ACTUAL_BACKUP_NAME=$(date +%Y_%m_%d_%H_%M_%S)
fi

# Save backup reference
echo "$ACTUAL_BACKUP_NAME" > "$BACKUP_REF_FILE"

log "Backup created: $ACTUAL_BACKUP_NAME"

# Restart services if we stopped them
if [ "$SERVICES_STOPPED" = true ]; then
    log "Restarting services..."
    docker compose up -d
fi

# Output backup name for scripting
if [ "$QUIET" = true ]; then
    echo "$ACTUAL_BACKUP_NAME"
fi

log "Backup complete."
