#!/bin/bash
#
# Backup Script
#
# Creates a backup of all databases (InfluxDB, MongoDB, Home Assistant).
#

set -euo pipefail

# Source docker helper functions
HELPER_SCRIPT="$(dirname "$0")/docker-helper.sh"
if [ ! -f "$HELPER_SCRIPT" ]; then
    echo "FATAL: Required helper library not found: $HELPER_SCRIPT" >&2
    exit 1
fi
# shellcheck source=scripts/docker-helper.sh
source "$HELPER_SCRIPT" || {
    echo "FATAL: Failed to load helper library: $HELPER_SCRIPT" >&2
    exit 1
}

# Lock file for preventing concurrent deployments
SKIP_LOCK=0

# Default values
BACKUP_NAME=""
STOP_SERVICES=0
YES_FLAG=0
QUIET=0
LIST_BACKUPS=0

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS] [BACKUP_NAME]

Create a backup of all databases (InfluxDB, MongoDB, Home Assistant).

Arguments:
  BACKUP_NAME         Optional name for the backup (default: timestamp YYYY_MM_DD_HH_MM_SS)

Options:
  -h, --help          Show this help message and exit
  -l, --list          List available backups and exit
  -s, --stop          Stop services before backup (recommended for consistency).
                      Fails if any container is still running, or starts
                      while the files are copied
  -y, --yes           Skip confirmation prompt
  -q, --quiet         Suppress output except errors (for scripting)

Examples:
  $(basename "$0")                    # Create backup with timestamp name
  $(basename "$0") pre-upgrade        # Create backup named 'pre-upgrade'
  $(basename "$0") -s -y              # Stop services, no confirmation
  $(basename "$0") -q                 # Quiet mode for scripts

Notes:
  - Backups are stored in the backup volume mounted by volman
  - Use 'rollback.sh --list' or 'restore.sh --list' to see available backups
  - For consistent backups, use --stop to stop services first
  - A backup gets its COMPLETE marker only when every volume and the MongoDB
    dump are in; restore.sh refuses a backup without it
  - InfluxDB alone is about 100 GB and takes about an hour to copy

EOF
    exit 0
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            usage
            ;;
        -l|--list)
            LIST_BACKUPS=1
            shift
            ;;
        -s|--stop)
            STOP_SERVICES=1
            shift
            ;;
        -y|--yes)
            YES_FLAG=1
            shift
            ;;
        -q|--quiet)
            QUIET=1
            YES_FLAG=1
            shift
            ;;
        --no-lock)
            # Internal flag: skip lock acquisition when called from deploy.sh/rollback.sh
            SKIP_LOCK=1
            shift
            ;;
        -*)
            echo "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
        *)
            BACKUP_NAME="$1"
            shift
            ;;
    esac
done

# Acquire lock if not skipped (internal flag for when called from deploy.sh/rollback.sh)
acquire_lock "$SKIP_LOCK"

# Change to project directory
cd "$PROJECT_DIR"

# Validate compose file exists
validate_compose_file

# Handle --list flag
if [ "$LIST_BACKUPS" -eq 1 ]; then
    list_backups
    exit 0
fi

# Validate backup name if provided by user
validate_backup_or_exit "$BACKUP_NAME"

# Show backup plan
if [ "$QUIET" -eq 0 ]; then
    echo ""
    echo "═══════════════════════════════════════════════════════════════"
    echo "                       BACKUP PLAN"
    echo "═══════════════════════════════════════════════════════════════"
    echo ""
    echo "  Backup name:     ${BACKUP_NAME:-<auto-generated timestamp>}"
    echo "  Stop services:   $STOP_SERVICES"
    echo ""
    echo "  This will backup:"
    echo "    - InfluxDB data"
    echo "    - MongoDB (mongodump archive)"
    echo "    - Home Assistant configuration"
    echo ""
    echo "═══════════════════════════════════════════════════════════════"
fi

if ! confirm "Proceed with backup?"; then
    log "Backup cancelled by user"
    exit 0
fi

# Stop services if requested
# Note: Use local variable instead of global SERVICES_STOPPED to avoid
# interfering with emergency restart trap when called with --no-lock
SERVICES_STOPPED_LOCAL=0
STATE_BEFORE=""

restart_stopped_services() {
    if [ "$SERVICES_STOPPED_LOCAL" -eq 1 ]; then
        log "Restarting services..."
        dc_run start || error "Failed to restart services - manual intervention required"
    fi
}

if [ "$STOP_SERVICES" -eq 1 ]; then
    log "Stopping services for consistent backup..."
    dc_run stop
    SERVICES_STOPPED_LOCAL=1

    # --stop is a request: something else (a cron job, a restart policy) can
    # start a container again. Check, and never tar a running database (#1589).
    if ! STATE_BEFORE=$(stack_run_state); then
        error "Could not check that the services stopped; not backing up"
        restart_stopped_services
        exit 1
    fi
    STILL_RUNNING=$(awk -F'\t' '$2 == "true" { print $1 }' <<<"$STATE_BEFORE")
    if [ -n "$STILL_RUNNING" ]; then
        error "Still running after stop; not backing up:" $STILL_RUNNING
        restart_stopped_services
        exit 1
    fi
fi

# Run backup
log "Creating backup..."
BACKUP_ARGS=()
[ -n "$BACKUP_NAME" ] && BACKUP_ARGS=("$BACKUP_NAME")

if ! BACKUP_OUTPUT=$(dc_run run --rm volman backup "${BACKUP_ARGS[@]}" 2>&1); then
    error "Backup failed"
    echo "$BACKUP_OUTPUT" >&2
    restart_stopped_services
    exit 1
fi

# Extract actual backup name from output using portable grep
ACTUAL_BACKUP_NAME=$(echo "$BACKUP_OUTPUT" | grep -o 'Creating backup [0-9_]*' | sed 's/Creating backup //' || echo "$BACKUP_NAME")
if [ -z "$ACTUAL_BACKUP_NAME" ]; then
    ACTUAL_BACKUP_NAME=$(date +%Y_%m_%d_%H_%M_%S)
fi

# The copy is consistent only if nothing started while it ran: the same
# containers, none running, none started since the check above.
if [ "$SERVICES_STOPPED_LOCAL" -eq 1 ]; then
    if ! STATE_AFTER=$(stack_run_state) || [ "$STATE_AFTER" != "$STATE_BEFORE" ]; then
        error "Containers started while backup $ACTUAL_BACKUP_NAME was being written; it is not consistent and is left without its COMPLETE marker"
        diff <(echo "$STATE_BEFORE") <(echo "${STATE_AFTER:-}") >&2 || true
        restart_stopped_services
        exit 1
    fi
fi

# MongoDB: a tar of a running mongod is not consistent, so dump it instead.
# The dump streams through volman into the backup directory.
if [ "$SERVICES_STOPPED_LOCAL" -eq 1 ]; then
    if ! dc_run start mongo; then
        error "Could not start mongo for the dump"
        restart_stopped_services
        exit 1
    fi
fi
if ! backup_mongo "$ACTUAL_BACKUP_NAME"; then
    error "MongoDB dump failed"
    restart_stopped_services
    exit 1
fi

# The COMPLETE manifest is what restore requires (#1590): written only now,
# after every volume and the dump are in.
SEAL_MODE=running
[ "$SERVICES_STOPPED_LOCAL" -eq 1 ] && SEAL_MODE=stopped
if ! dc_run run --rm volman seal "$ACTUAL_BACKUP_NAME" "$SEAL_MODE" >&2; then
    error "Could not write the COMPLETE marker of backup $ACTUAL_BACKUP_NAME"
    restart_stopped_services
    exit 1
fi

# Only a complete backup (files, dump and marker) becomes the one rollback points at
save_backup_reference "$ACTUAL_BACKUP_NAME"

log "Backup created: $ACTUAL_BACKUP_NAME"

restart_stopped_services

# Output backup name for scripting
if [ "$QUIET" -eq 1 ]; then
    echo "$ACTUAL_BACKUP_NAME"
fi

log "Backup complete."
