#!/bin/bash
# docker-helper.sh
# Helper script for docker-compose version compatibility and common utilities
# Source this script in other scripts with: source "$(dirname "$0")/docker-helper.sh"
#
# Minimum requirements:
# - Bash 4.4+ (associative arrays, empty arrays under set -u)
# - Git 1.8.5+
# - jq (for health checks and service status)
# - flock (for deployment locking)
# - curl (for notifications, optional)
# - docker compose v2 (deploy.sh and the health gate)

set -euo pipefail

# Initialize project directories if not already set
# This is done automatically when the script is sourced
if [ -z "${SCRIPT_DIR:-}" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    export SCRIPT_DIR
fi

if [ -z "${PROJECT_DIR:-}" ]; then
    PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
    export PROJECT_DIR
fi

# Standard file paths
LOCK_FILE="${LOCK_FILE:-/var/lock/homy-deployment.lock}"
VERSION_FILE="${VERSION_FILE:-$PROJECT_DIR/.deployed-version}"
PREVIOUS_VERSION_FILE="${PREVIOUS_VERSION_FILE:-$PROJECT_DIR/.previous-version}"
BACKUP_REF_FILE="${BACKUP_REF_FILE:-$PROJECT_DIR/.pre-upgrade-backup}"
# Name of the ZFS snapshot the last deploy took (written by snapshot.sh)
SNAPSHOT_REF_FILE="${SNAPSHOT_REF_FILE:-$PROJECT_DIR/.pre-deploy-snapshot}"
# Generated by deploy.sh: pins every service to its image digest and labels it
# with a hash of the host files it mounts. Not in git.
DEPLOY_OVERRIDE_FILE="${DEPLOY_OVERRIDE_FILE:-$PROJECT_DIR/docker-compose.deploy.yml}"

# Container label holding the hash of the config files a service mounts
CONFIG_HASH_LABEL="homy.config-files-hash"
# Compose label marking a service whose data format only migrates forward
STATEFUL_LABEL="homy.stateful"

# Service state tracking for emergency restart
SERVICES_STOPPED="${SERVICES_STOPPED:-0}"

# Health gate tuning (seconds). A service without a healthcheck passes once it
# has run this long without a restart.
HEALTH_STABLE_SECONDS="${HEALTH_STABLE_SECONDS:-30}"
HEALTH_POLL_INTERVAL="${HEALTH_POLL_INTERVAL:-5}"
# Added on top of the longest start period + interval x retries + timeout
HEALTH_GATE_MARGIN="${HEALTH_GATE_MARGIN:-60}"

# Detect docker-compose command (with or without dash)
# Prefers docker compose 2.x (plugin) over docker-compose 1.x (standalone)
detect_docker_compose() {
    if docker compose version &> /dev/null; then
        # New version as plugin (docker compose 2.x) - preferred
        echo "docker compose"
    elif command -v docker-compose &> /dev/null; then
        # Old version with dash (docker-compose 1.x)
        echo "docker-compose"
    else
        echo "ERROR: Neither 'docker compose' nor 'docker-compose' command is available" >&2
        exit 1
    fi
}

# Global variable to store the docker-compose command
readonly DOCKER_COMPOSE_CMD="${DOCKER_COMPOSE_CMD:-$(detect_docker_compose)}"

# Check if docker-compose supports JSON format output
# Returns 0 if supported, 1 if not
# Note: $DOCKER_COMPOSE_CMD is intentionally unquoted for word splitting (see dc_run comment)
supports_json_format() {
    # Try the command and check if it accepts --format flag
    $DOCKER_COMPOSE_CMD ps --format json &> /dev/null
    local result=$?
    # If exit code is 0 or the command doesn't error on the flag, it's supported
    return $result
}

# Wrapper function for docker-compose commands
# Usage: dc_run [docker-compose args...]
# Example: dc_run ps --format json
# Note: $DOCKER_COMPOSE_CMD is intentionally unquoted to allow word splitting
# for "docker compose" (two words). This is safe because:
# - DOCKER_COMPOSE_CMD is readonly
# - Only set by detect_docker_compose() with hardcoded safe values
# - Not user-controllable
dc_run() {
    $DOCKER_COMPOSE_CMD "$@"
}

# Get running service count (version-aware)
# Returns count of running services
# Works with both v1.x (text parsing) and v2.x (JSON)
get_running_services_count() {
    if supports_json_format; then
        # v2.x or v1.28+ with JSON support
        require_jq
        dc_run ps --format json 2>/dev/null | jq -rs '[.[] | select(.State == "running")] | length' || echo "0"
    else
        # v1.27.4 and earlier - parse text output
        # Count lines with "Up" status, excluding header
        # Use word boundary (\b) to match " Up" followed by non-word char:
        # - "Up" (simple running, end of line)
        # - "Up (health: starting)" (with health check)
        # - "Up 5 seconds" (with uptime)
        # - "Up       0.0.0.0:..." (with port mappings)
        # Prevents false positives like "UpgradeDB" in command column
        dc_run ps 2>/dev/null | grep -cE " Up\b" || echo "0"
    fi
}

# Get unhealthy service names (version-aware)
# Returns space-separated list of unhealthy service names
get_unhealthy_services() {
    if supports_json_format; then
        # v2.x or v1.28+ with JSON support
        require_jq
        dc_run ps --format json 2>/dev/null | \
            jq -rs '[.[] | select(.Health == "unhealthy")] | .[].Name' 2>/dev/null | \
            head -5 || echo ""
    else
        # v1.27.4 and earlier - parse text output
        # This is a best-effort approach as v1.x doesn't expose health status in ps output
        # We'll return empty string as we can't reliably detect health without JSON
        echo ""
    fi
}

# Get starting service names (version-aware)
# Returns space-separated list of starting service names
get_starting_services() {
    if supports_json_format; then
        # v2.x or v1.28+ with JSON support
        require_jq
        dc_run ps --format json 2>/dev/null | \
            jq -rs '[.[] | select(.Health == "starting")] | .[].Name' 2>/dev/null | \
            head -5 || echo ""
    else
        # v1.27.4 and earlier - parse text output
        # Look for services that are "Up" but may still be starting
        # This is approximate as v1.x doesn't expose health status clearly
        echo ""
    fi
}

# Logging function with timestamp
# Usage: log "message"
# If LOG_FILE is set, logs to both stdout and file
log() {
    if [ "${QUIET:-0}" -eq 0 ]; then
        local message="[$(date '+%Y-%m-%d %H:%M:%S')] $*"
        if [ -n "${LOG_FILE:-}" ]; then
            echo "$message" | tee -a "$LOG_FILE"
        else
            echo "$message"
        fi
    fi
}

# Error logging function - never suppressed by QUIET mode
# Usage: error "message"
# Always outputs to stderr and log file (if set)
error() {
    local message="[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $*"
    echo "$message" >&2
    if [ -n "${LOG_FILE:-}" ]; then
        echo "$message" >> "$LOG_FILE"
    fi
}

# Confirmation prompt with y/N response
# Usage: if confirm "Are you sure?"; then ...; fi
# Respects YES_FLAG (-y) to skip prompts
confirm() {
    local prompt="$1"

    if [ "${YES_FLAG:-0}" -eq 1 ] || [ "${QUIET:-0}" -eq 1 ]; then
        return 0
    fi

    echo ""
    read -rp "$prompt [y/N] " response
    case "$response" in
        [yY][eE][sS]|[yY])
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

# Notification function for Telegram (optional)
# Usage: notify "message"
# Requires TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID to be set
#
# Each Bot API call is recorded as one JSON line in the journal, tagged with
# NOTIFY_SENDER (default homy-deploy; rollback.sh sets homy-rollback):
#   journalctl -t homy-deploy
# The Bot API cannot list what a bot sent, so this line is the only history.
# The line has the full text and never the bot token or the chat id.
# Never fails the caller: a notification problem must not stop a deploy.
notify() {
    local message="$1"
    local sender="${NOTIFY_SENDER:-homy-deploy}"

    if [ -z "${TELEGRAM_BOT_TOKEN:-}" ] || [ -z "${TELEGRAM_CHAT_ID:-}" ]; then
        return 0
    fi

    # No -f: on an API error the body carries the reason and is wanted.
    # No -S: curl's own error text can echo the URL, which holds the token.
    # --data-urlencode keeps & and + in the text intact.
    local reply rc=0
    reply=$(curl -s --max-time 30 -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
        --data-urlencode "chat_id=${TELEGRAM_CHAT_ID}" \
        --data-urlencode "text=${message}" \
        --data-urlencode "parse_mode=HTML" 2>/dev/null) || rc=$?

    if command -v jq &> /dev/null && command -v systemd-cat &> /dev/null; then
        jq -nc --arg sender "$sender" --arg text "$message" --arg reply "$reply" --arg rc "$rc" '
            (try ($reply | fromjson) catch null | if type == "object" then . else {} end) as $r
            | {
                event: "telegram.sent",
                sender: $sender,
                source: null,
                origin_host: "routy",
                ok: ($r.ok == true),
                message_id: (if $r.ok == true then (($r.result | objects | .message_id) // null) else null end),
                error: (if $r.ok == true then null
                        elif ($r.description | type) == "string" then $r.description
                        elif $rc != "0" then "curl exit " + $rc
                        else "unreadable reply from the Bot API" end),
                text: $text
            }' 2>/dev/null | systemd-cat -t "$sender" 2>/dev/null || true
    fi

    return 0
}

# Dump the app database of the running mongo container into the backup
# <name> as mongo.archive.gz, through volman (which owns the backup directory).
# Waits up to a minute for mongod to accept connections, since it may have
# just been started.
# Usage: backup_mongo "backup_name"
backup_mongo() {
    local name="$1" try
    for try in $(seq 1 30); do
        if dc_run exec -T mongo sh -c 'mongosh --quiet --eval "db.adminCommand(\"ping\")" >/dev/null 2>&1'; then
            break
        fi
        [ "$try" -eq 30 ] && return 1
        sleep 2
    done
    # pipefail: a failed mongodump must fail the backup, not leave a short file
    (
        set -o pipefail
        dc_run exec -T mongo sh -c 'mongodump --archive --gzip --db "$MONGO_INITDB_DATABASE" --authenticationDatabase admin -u "$(cat /run/secrets/mongo_root_username)" -p "$(cat /run/secrets/mongo_root_password)"' \
            | dc_run run --rm -T volman store "$name" mongo.archive.gz >&2
    )
}

# Directory holding the secret files. SECRETS_PATH from the environment, else
# the last SECRETS_PATH= line of the project's .env (what docker-compose uses,
# so both agree), else ./secrets (this script's own fallback). A relative value
# is relative to the project directory, "~" is the home directory. The .env
# line is read, not sourced; a value with a $ in it (as in example.env) is
# ignored.
# Usage: resolve_secrets_dir
# The value of the last NAME= line of the project's .env (read, not sourced),
# without quotes or a trailing comment. Empty when there is none.
# Usage: dotenv_value NAME
dotenv_value() {
    local name="$1" project_dir="${PROJECT_DIR:-$(pwd)}" value
    [ -f "$project_dir/.env" ] || return 0
    value=$(sed -n -E "s/^[[:space:]]*(export[[:space:]]+)?${name}[[:space:]]*=[[:space:]]*//p" "$project_dir/.env" 2>/dev/null | tail -n1 | tr -d '\r' || true)
    case "$value" in
        \"*) value="${value#\"}"; value="${value%%\"*}" ;;
        \'*) value="${value#\'}"; value="${value%%\'*}" ;;
        *)   value="${value%%[[:space:]]#*}"; value="${value%"${value##*[![:space:]]}"}" ;;
    esac
    echo "$value"
}

resolve_secrets_dir() {
    local project_dir="${PROJECT_DIR:-$(pwd)}"
    local dir="${SECRETS_PATH:-}"

    if [ -z "$dir" ]; then
        dir=$(dotenv_value SECRETS_PATH)
    fi

    case "$dir" in
        ''|*'$'*) dir="secrets" ;;
    esac
    case "$dir" in
        /*) ;;
        '~'|'~/'*) dir="$HOME${dir#\~}" ;;
        *) dir="$project_dir/${dir#./}" ;;
    esac
    echo "$dir"
}

# Load Telegram notification secrets if available
# Usage: load_notification_secrets
load_notification_secrets() {
    local secrets_dir
    secrets_dir=$(resolve_secrets_dir)

    if [ -f "$secrets_dir/telegram_bot_token" ]; then
        TELEGRAM_BOT_TOKEN=$(cat "$secrets_dir/telegram_bot_token")
    fi

    if [ -f "$secrets_dir/telegram_chat_id" ]; then
        TELEGRAM_CHAT_ID=$(cat "$secrets_dir/telegram_chat_id")
    fi

    if [ -z "${TELEGRAM_BOT_TOKEN:-}" ] || [ -z "${TELEGRAM_CHAT_ID:-}" ]; then
        echo "Telegram secrets not found in $secrets_dir; notifications are off" >&2
    fi
}

# Acquire deployment lock to prevent concurrent operations
# Usage: acquire_lock [SKIP_LOCK]
# Uses flock on /var/lock/homy-deployment.lock
# Pass 1 or set SKIP_LOCK=1 to skip locking (for internal script calls)
acquire_lock() {
    local skip_lock="${1:-${SKIP_LOCK:-0}}"
    local lock_name="${LOCK_NAME:-deployment}"

    if ! command -v flock &> /dev/null; then
        error "flock is required but not installed."
        echo "Install with: apt-get install util-linux" >&2
        exit 1
    fi

    if [ "$skip_lock" -eq 0 ]; then
        exec 200>"$LOCK_FILE"

        if ! flock -n 200; then
            error "Another $lock_name operation is in progress"
            echo "If you're sure no other operation is running, remove: $LOCK_FILE" >&2
            exit 1
        fi
    fi
}

# Validate backup name format
# Usage: validate_backup_name "backup_name"
# Returns 0 if valid, 1 if invalid
validate_backup_name() {
    local name="$1"

    # Check for invalid characters (only alphanumeric, underscore, dash allowed)
    if ! [[ "$name" =~ ^[a-zA-Z0-9_-]+$ ]]; then
        error "Invalid backup name format. Only alphanumeric characters, underscores, and dashes are allowed."
        return 1
    fi

    # Prevent path traversal
    if [[ "$name" == *".."* ]] || [[ "$name" == *"/"* ]]; then
        error "Invalid backup name. Path traversal characters are not allowed."
        return 1
    fi

    return 0
}

# Validate image tag format
# Usage: validate_image_tag "tag"
# Returns 0 if valid, 1 if invalid
validate_image_tag() {
    local tag="$1"

    # Allow git SHAs (40 hex chars), semantic versions, branch names, or 'latest'
    if [[ "$tag" =~ ^[0-9a-f]{40}$ ]] || \
       [[ "$tag" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?$ ]] || \
       [[ "$tag" =~ ^[a-zA-Z0-9/_-]+$ ]] || \
       [[ "$tag" == "latest" ]]; then
        return 0
    fi

    error "Invalid image tag format: $tag"
    echo "Allowed formats: git SHA, semantic version (v1.2.3), branch name, or 'latest'" >&2
    return 1
}

# Check if services are running
# Usage: services_running
# Returns 0 if any services are running, 1 if all stopped, 2 on error
# Works with both v1.x (text parsing) and v2.x (JSON)
services_running() {
    local running_count
    running_count=$(get_running_services_count)

    if [ "$running_count" = "0" ]; then
        return 1  # No services running
    elif [ "$running_count" -gt 0 ]; then
        return 0  # Services are running
    else
        return 2  # Error occurred
    fi
}

# Warning to stderr (and the log file). Safe inside $(...): stdout stays clean.
# Usage: warn "message"
warn() {
    local message
    message="[$(date '+%Y-%m-%d %H:%M:%S')] WARNING: $*"
    echo "$message" >&2
    if [ -n "${LOG_FILE:-}" ]; then
        echo "$message" >> "$LOG_FILE"
    fi
}

# Require docker compose v2 or newer. The deploy flow and the health gate use
# v2-only features (--no-build/--pull never on up, config --hash, per-service
# ps). docker-compose 1.x cannot report health, and a gate that cannot check
# must not pass (#1545).
# Usage: require_compose_v2
require_compose_v2() {
    local version major

    if [ "$DOCKER_COMPOSE_CMD" != "docker compose" ]; then
        error "docker compose v2 is required; this host has only '$DOCKER_COMPOSE_CMD'"
        return 1
    fi

    version=$(dc_run version --short 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -n1) || version=""
    major="${version%%.*}"
    if ! [[ "$major" =~ ^[0-9]+$ ]] || [ "$major" -lt 2 ]; then
        error "docker compose v2 or newer is required (found version '${version:-unknown}')"
        return 1
    fi
}

# The compose files the host uses, as a COMPOSE_FILE value, without the
# generated deploy override: COMPOSE_FILE from the environment, else from
# .env, else docker-compose.yml (plus docker-compose.override.yml when the
# host has one - naming the files turns off compose's automatic pick-up).
# Relative paths are relative to the project directory.
# Usage: compose_base_files
compose_base_files() {
    local value="${COMPOSE_FILE:-}" files="" f
    [ -n "$value" ] || value=$(dotenv_value COMPOSE_FILE)
    case "$value" in *'$'*) value="" ;; esac

    if [ -z "$value" ]; then
        value="docker-compose.yml"
        if [ -f "$PROJECT_DIR/docker-compose.override.yml" ]; then
            value="$value:docker-compose.override.yml"
        fi
    fi

    local IFS=':'
    for f in $value; do
        [ -n "$f" ] || continue
        case "$f" in /*) ;; *) f="$PROJECT_DIR/${f#./}" ;; esac
        [ "$f" = "$DEPLOY_OVERRIDE_FILE" ] && continue
        files="${files:+$files:}$f"
    done
    echo "${files:-$PROJECT_DIR/docker-compose.yml}"
}

# Compose with the committed files only (what images and mounts the code asks for)
# Usage: dc_base [docker compose args...]
dc_base() {
    COMPOSE_FILE="$(compose_base_files)" dc_run "$@"
}

# Compose with the generated digest/config-hash override on top
# Usage: dc_deploy [docker compose args...]
dc_deploy() {
    COMPOSE_FILE="$(compose_base_files):$DEPLOY_OVERRIDE_FILE" dc_run "$@"
}

# Services that are meant to keep running: all except `restart: "no"` (one-shot
# tools such as volman and the historians, which the deploy leaves alone).
# Usage: long_running_services <compose config json file>
long_running_services() {
    jq -r '.services | to_entries[] | select((.value.restart // "") != "no") | .key' "$1" | LC_ALL=C sort
}

# Services labelled homy.stateful=true: their data format migrates forward only
# (HA recorder, zigbee2mqtt database, Mongo, Grafana, InfluxDB), so their image
# is never rolled back automatically.
# Usage: stateful_services <compose config json file>
stateful_services() {
    jq -r --arg l "$STATEFUL_LABEL" '.services | to_entries[] | select((.value.labels // {})[$l] == "true") | .key' "$1" | LC_ALL=C sort
}

# Writable host directories that hold the stack's state, one "service<TAB>path"
# per line: writable bind mounts of long-running services, minus system paths
# (/dev, /lib/modules, the docker socket and the like).
# Usage: persistent_mounts <compose config json file>
persistent_mounts() {
    jq -r '
        .services | to_entries[]
        | select((.value.restart // "") != "no")
        | .key as $svc
        | (.value.volumes // [])[]
        | select(.type == "bind" and ((.read_only // false) | not))
        | select(.source | test("^/(dev|proc|sys|run|var/run|lib|lib64|usr|etc|boot)(/|$)") | not)
        | [$svc, .source] | @tsv
    ' "$1"
}

# Docker volumes (named or declared) that long-running services use for state,
# one "service<TAB>volume" per line. A snapshot of the host dataset does not
# cover them.
# Usage: compose_state_volumes <compose config json file>
compose_state_volumes() {
    jq -r '
        .services | to_entries[]
        | select((.value.restart // "") != "no")
        | .key as $svc
        | (.value.volumes // [])[]
        | select(.type == "volume")
        | [$svc, (.source // "(anonymous)")] | @tsv
    ' "$1"
}

# Hash of every host file a service reads its configuration from: read-only
# bind mounts (files, or every file under a directory), secret files and
# env_files. Data is left out, so the hash changes only when configuration
# does: writable mounts, and read-only mounts that overlap some service's
# writable mount (ingress reads the nginx config ingressgen writes, with
# container addresses in it). Unreadable files are warned about and left out.
# Set HASH_CACHE_DIR to reuse the hash of a path across services.
# Usage: service_config_files_hash <compose config json file> <service>
service_config_files_hash() {
    local config="$1" svc="$2" kind path

    jq -r --arg s "$svc" '
        . as $root
        | [ .services[] | (.volumes // [])[] | select(.type == "bind" and ((.read_only // false) | not)) | .source ] as $rw
        | def overlaps($p): any($rw[]; . == $p or startswith($p + "/") or ($p | startswith(. + "/")));
        .services[$s] as $svc
        | ( ($svc.volumes // [])[] | select(.type == "bind" and (.read_only // false)) | .source
            | select(overlaps(.) | not) | "mount\t" + . ),
          ( ($svc.secrets // [])[] | "secret\t" + (($root.secrets // {})[.source].file // "") ),
          ( ($svc.env_file // [])[] | "env_file\t" + (if type == "string" then . else .path end) )
    ' "$config" | while IFS=$'\t' read -r kind path; do
        _hash_host_path "$kind" "$path"
    done | LC_ALL=C sort | sha256sum | cut -c1-64
}

# One "kind<TAB>path<TAB>sha256" line per regular file at or under <path>.
# Sockets and devices (the docker socket) have no content to hash.
_hash_host_path() {
    local kind="$1" path="$2" key

    [ -n "$path" ] || return 0
    if [ -S "$path" ] || [ -c "$path" ] || [ -b "$path" ] || [ -p "$path" ]; then
        return 0
    fi

    if [ -n "${HASH_CACHE_DIR:-}" ]; then
        key=$(printf '%s\t%s' "$kind" "$path" | sha256sum | cut -c1-64)
        if [ -f "$HASH_CACHE_DIR/$key" ]; then
            cat "$HASH_CACHE_DIR/$key"
            return 0
        fi
        _hash_host_path_uncached "$kind" "$path" | tee "$HASH_CACHE_DIR/$key.tmp"
        mv "$HASH_CACHE_DIR/$key.tmp" "$HASH_CACHE_DIR/$key"
    else
        _hash_host_path_uncached "$kind" "$path"
    fi
}

_hash_host_path_uncached() {
    local kind="$1" path="$2" file line sum

    if [ -d "$path" ]; then
        while IFS= read -r -d '' file; do
            warn "cannot read $file: a change to it will not recreate its service"
        done < <(find "$path" \( -type f -o -type d \) ! -readable -print0 2>/dev/null || true)
        # One sha256sum for many files; output is "<sum>  <path>". find exits
        # 1 on an unreadable directory, already warned about above.
        { find "$path" -type f -readable -print0 2>/dev/null || true; } \
            | xargs -0 -r sha256sum 2>/dev/null \
            | while IFS= read -r line; do
                printf '%s\t%s\t%s\n' "$kind" "${line#*  }" "${line%%  *}"
            done
    elif [ -e "$path" ]; then
        if [ -r "$path" ] && sum=$(sha256sum < "$path" 2>/dev/null); then
            printf '%s\t%s\t%s\n' "$kind" "$path" "${sum%% *}"
        else
            warn "cannot read $path: a change to it will not recreate its service"
        fi
    else
        printf '%s\t%s\tmissing\n' "$kind" "$path"
    fi
}

# The registry digest reference (repo@sha256:...) of a local image. CI's
# retag copies the manifest, so an unchanged service keeps its digest from
# one commit's tag to the next.
# Usage: image_repo_digest <image reference>
image_repo_digest() {
    local image="$1" repo last digests digest

    repo="${image%@*}"
    last="${repo##*/}"
    if [[ "$last" == *:* ]]; then
        repo="${repo%:*}"
    fi

    if ! digests=$(docker image inspect --format '{{json .RepoDigests}}' "$image" 2>/dev/null); then
        error "Image $image is not on this host (did the pull finish?)"
        return 1
    fi

    digest=$(jq -r --arg r "$repo" '(. // [])[] | select(startswith($r + "@"))' <<<"$digests" | head -n1)
    if [ -z "$digest" ]; then
        warn "$image has no registry digest; it stays pinned by tag and is recreated on every deploy"
        echo "$image"
        return 0
    fi
    echo "$digest"
}

# Write the deploy override: every service pinned to its image digest and
# labelled with the hash of its config files. Compose recreates a container
# when its config hash changes, so with the override an unchanged service
# keeps its hash (and keeps running), while a new image, a compose change, an
# .env change or an edited mounted config file each change it.
# JSON is valid YAML, so compose reads the file as is.
# Usage: generate_deploy_override <compose config json file> <output file>
generate_deploy_override() {
    local config="$1" out="$2" image digest svc hash
    local pins="{}" labels="{}"

    while IFS= read -r image; do
        [ -n "$image" ] || continue
        digest=$(image_repo_digest "$image") || return 1
        pins=$(jq -c --arg i "$image" --arg d "$digest" '. + {($i): $d}' <<<"$pins")
    done < <(jq -r '[.services[] | .image // empty] | unique[]' "$config")

    # Several services mount the same paths (/usr/share/zoneinfo): hash each once
    local cache
    cache=$(mktemp -d)
    while IFS= read -r svc; do
        if ! hash=$(HASH_CACHE_DIR="$cache" service_config_files_hash "$config" "$svc"); then
            rm -rf "$cache"
            return 1
        fi
        labels=$(jq -c --arg s "$svc" --arg h "$hash" '. + {($s): $h}' <<<"$labels")
    done < <(jq -r '.services | keys[]' "$config")
    rm -rf "$cache"

    if ! jq --argjson pins "$pins" --argjson labels "$labels" --arg label "$CONFIG_HASH_LABEL" '
        {
          "x-generated-by": "scripts/deploy.sh - do not edit",
          services: (.services | with_entries(.value =
            ((if .value.image then {image: $pins[.value.image]} else {} end)
             + {labels: {($label): $labels[.key]}})))
        }' "$config" > "$out.tmp.$$"; then
        rm -f "$out.tmp.$$"
        error "Could not write $out"
        return 1
    fi
    mv "$out.tmp.$$" "$out"
}

# The services compose will create or recreate on the next `dc_deploy up`:
# no container yet, or the config hash compose computes now differs from the
# com.docker.compose.config-hash label on the container. Only logged; the
# health gate works from what actually changed.
# Usage: predict_recreate <service...>
predict_recreate() {
    local expected current="" ids svc want have

    expected=$(dc_deploy config --hash '*') || return 1
    ids=$(dc_run ps -a -q) || return 1
    if [ -n "$ids" ]; then
        # shellcheck disable=SC2086
        current=$(docker inspect $ids | jq -r '.[] | [.Config.Labels["com.docker.compose.service"] // "", .Config.Labels["com.docker.compose.config-hash"] // ""] | @tsv') || return 1
    fi

    for svc in "$@"; do
        want=$(awk -v s="$svc" '$1 == s { print $2; exit }' <<<"$expected")
        have=$(awk -F'\t' -v s="$svc" '$1 == s { print $2; exit }' <<<"$current")
        if [ -z "$have" ] || [ "$want" != "$have" ]; then
            echo "$svc"
        fi
    done
}

# One line per container of the project: service, container id, image id,
# start time, status. Taken before and after `up` to see what changed.
# Usage: container_states > file
container_states() {
    local ids
    ids=$(dc_run ps -a -q) || return 1
    [ -n "$ids" ] || return 0
    # shellcheck disable=SC2086
    docker inspect $ids | jq -r '.[] | [.Config.Labels["com.docker.compose.service"] // "?", .Id, .Image, .State.StartedAt, .State.Status] | @tsv' | LC_ALL=C sort
}

# Services the deploy changed, between two container_states files: a new or
# replaced container (new id), or one that was not running before and was
# started. A container that merely restarted by itself (already crash-looping
# before the deploy) is not counted.
# Usage: changed_services <before file> <after file>
changed_services() {
    awk -F'\t' 'FILENAME == ARGV[1] { id[$1] = $2; started[$1] = $4; status[$1] = $5; next }
                !($1 in id) || id[$1] != $2 || (status[$1] != "running" && started[$1] != $4) { print $1 }' "$1" "$2" | LC_ALL=C sort -u
}

# Services whose container now runs a different image (or is new) between
# two container_states files.
# Usage: image_changed_services <before file> <after file>
image_changed_services() {
    awk -F'\t' 'FILENAME == ARGV[1] { before[$1] = $3; next }
                !($1 in before) || before[$1] != $3 { print $1 }' "$1" "$2" | LC_ALL=C sort -u
}

# One "container<TAB>running<TAB>started at" line per container of the
# project, stopped ones included. backup.sh compares two of these to prove
# nothing started while it was copying.
# Usage: stack_run_state
stack_run_state() {
    local ids
    ids=$(dc_run ps -a -q 2>/dev/null) || ids=$(dc_run ps -q) || return 1
    [ -n "$ids" ] || return 0
    # shellcheck disable=SC2086
    docker inspect $ids | jq -r '.[] | [.Name, (.State.Running | tostring), .State.StartedAt] | @tsv' | LC_ALL=C sort
}

# Clock and sleep of the health gate; the tests replace these two.
_gate_now() { date +%s; }
_gate_sleep() { sleep "$1"; }

# Per container: service, restart policy, has healthcheck, start period,
# interval, retries, timeout (seconds; 0 = docker default), status, health,
# restart count, start time.
# shellcheck disable=SC2089,SC2090  # a jq program, not a shell command
_GATE_JQ='.[] | [
    .Config.Labels["com.docker.compose.service"] // "?",
    ((.HostConfig.RestartPolicy.Name // "") | if . == "" then "no" else . end),
    (if ((.Config.Healthcheck.Test // []) | length) > 0 and (.Config.Healthcheck.Test[0] != "NONE") then "yes" else "no" end),
    (((.Config.Healthcheck.StartPeriod // 0) / 1000000000) | floor),
    (((.Config.Healthcheck.Interval // 0) / 1000000000) | floor),
    (.Config.Healthcheck.Retries // 0),
    (((.Config.Healthcheck.Timeout // 0) / 1000000000) | floor),
    (.State.Status // "unknown"),
    (.State.Health.Status // "none"),
    (.RestartCount // 0),
    ((.State.StartedAt // "") | if . == "" then "never" else . end)
] | map(tostring) | @tsv'

# Health gate for the services a deploy recreated.
#   - a service with a healthcheck passes when docker reports it healthy, and
#     fails as soon as it is unhealthy, exited or dead;
#   - a service without one passes once it is running and its restart count
#     has not changed for HEALTH_STABLE_SECONDS (30 s);
#   - one-shot services (restart: "no") are skipped.
# The timeout is the longest start period + interval x retries + timeout of
# the services waited on, plus HEALTH_GATE_MARGIN.
# Returns 0 when all pass, 1 when one fails or the time runs out, 2 when the
# gate cannot check at all (no compose v2, no jq, no container, inspect fails).
# The failures are left in HEALTH_GATE_FAILURES.
# Usage: health_gate <service...>
health_gate() {
    HEALTH_GATE_FAILURES=""
    if [ "$#" -eq 0 ]; then
        log "Health gate: no service was recreated, nothing to check"
        return 0
    fi

    if ! command -v jq &> /dev/null; then
        error "Health gate cannot check anything: jq is not installed"
        return 2
    fi
    if ! require_compose_v2; then
        error "Health gate cannot check anything without docker compose v2"
        return 2
    fi

    local -A cid=() base_rc=() base_started=() base_time=() last=()
    local svc id rows row policy hc sp iv rt to status health rc started
    local timeout="$HEALTH_STABLE_SECONDS" need pending=() still=() failed=() ids=()

    for svc in "$@"; do
        id=$(dc_run ps -a -q "$svc" 2>/dev/null | head -n1) || id=""
        if [ -z "$id" ]; then
            error "Health gate cannot check $svc: it has no container"
            return 2
        fi
        cid[$svc]="$id"
    done

    for svc in "$@"; do ids+=("${cid[$svc]}"); done
    if ! rows=$(docker inspect "${ids[@]}" 2>/dev/null | jq -r "$_GATE_JQ") || [ -z "$rows" ]; then
        error "Health gate cannot check: docker inspect failed for $*"
        return 2
    fi

    for svc in "$@"; do
        row=$(awk -F'\t' -v s="$svc" '$1 == s { print; exit }' <<<"$rows")
        if [ -z "$row" ]; then
            error "Health gate cannot check $svc: docker inspect did not return it"
            return 2
        fi
        IFS=$'\t' read -r _ policy hc sp iv rt to status health rc started <<<"$row"
        if [ "$policy" = "no" ]; then
            log "  $svc: skipped (one-shot, restart: no)"
            continue
        fi
        pending+=("$svc")
        if [ "$hc" = "yes" ]; then
            [ "$iv" -gt 0 ] || iv=30
            [ "$to" -gt 0 ] || to=30
            [ "$rt" -gt 0 ] || rt=3
            need=$((sp + iv * rt + to))
            [ "$need" -le "$timeout" ] || timeout="$need"
        fi
    done

    if [ "${#pending[@]}" -eq 0 ]; then
        log "Health gate: only one-shot services changed, nothing to wait for"
        return 0
    fi

    timeout=$((timeout + HEALTH_GATE_MARGIN))
    log "Health gate: waiting up to ${timeout}s for: ${pending[*]}"

    local start now
    start=$(_gate_now)
    while :; do
        now=$(_gate_now)
        ids=()
        for svc in "${pending[@]}"; do ids+=("${cid[$svc]}"); done
        if ! rows=$(docker inspect "${ids[@]}" 2>/dev/null | jq -r "$_GATE_JQ"); then
            error "Health gate cannot check: docker inspect failed for ${pending[*]}"
            return 2
        fi

        still=()
        for svc in "${pending[@]}"; do
            row=$(awk -F'\t' -v s="$svc" '$1 == s { print; exit }' <<<"$rows")
            if [ -z "$row" ]; then
                error "Health gate cannot check $svc: its container is gone"
                return 2
            fi
            IFS=$'\t' read -r _ policy hc sp iv rt to status health rc started <<<"$row"

            if [ "$hc" = "yes" ]; then
                if [ "$health" = "unhealthy" ]; then
                    failed+=("$svc (unhealthy)")
                    continue
                fi
                case "$status" in
                    exited|dead)
                        failed+=("$svc ($status)")
                        continue
                        ;;
                esac
                if [ "$status" = "running" ] && [ "$health" = "healthy" ]; then
                    log "  $svc: healthy"
                    continue
                fi
                last[$svc]="$status, health $health"
            elif [ "$status" = "running" ]; then
                if [ "${base_rc[$svc]:-}" != "$rc" ] || [ "${base_started[$svc]:-}" != "$started" ]; then
                    base_rc[$svc]="$rc"
                    base_started[$svc]="$started"
                    base_time[$svc]="$now"
                fi
                if [ $((now - base_time[$svc])) -ge "$HEALTH_STABLE_SECONDS" ]; then
                    log "  $svc: running, no restart for ${HEALTH_STABLE_SECONDS}s"
                    continue
                fi
                last[$svc]="running, restart count $rc"
            else
                unset "base_rc[$svc]" "base_started[$svc]" "base_time[$svc]"
                last[$svc]="$status"
            fi
            still+=("$svc")
        done

        if [ "${#failed[@]}" -gt 0 ]; then
            break
        fi
        if [ "${#still[@]}" -eq 0 ]; then
            log "Health gate passed"
            return 0
        fi
        pending=("${still[@]}")
        if [ $((now - start)) -ge "$timeout" ]; then
            for svc in "${pending[@]}"; do
                failed+=("$svc (still ${last[$svc]} after ${timeout}s)")
            done
            break
        fi
        _gate_sleep "$HEALTH_POLL_INTERVAL"
    done

    # shellcheck disable=SC2034  # read by deploy.sh
    HEALTH_GATE_FAILURES="${failed[*]}"
    error "Health gate failed: ${failed[*]}"
    return 1
}

# Health gate over every long-running service of the current compose files.
# Used by rollback.sh, which restarts the whole stack.
# Usage: wait_for_health
wait_for_health() {
    local config services rc=0

    if ! command -v jq &> /dev/null; then
        error "Health gate cannot check anything: jq is not installed"
        return 2
    fi
    config=$(mktemp)
    if ! dc_run config --format json > "$config" 2>/dev/null; then
        rm -f "$config"
        error "Health gate cannot check: could not read the compose config"
        return 2
    fi
    services=$(long_running_services "$config")
    rm -f "$config"
    # shellcheck disable=SC2086
    health_gate $services || rc=$?
    return "$rc"
}

# Atomic file write (write to temp then move)
# Usage: atomic_write "filename" "content"
# Returns 0 on success, 1 on failure
atomic_write() {
    local filename="$1"
    local content="$2"
    local temp_file="${filename}.tmp.$$"  # Include PID for uniqueness

    # Write to temp file with error handling
    if ! echo "$content" > "$temp_file" 2>/dev/null; then
        rm -f "$temp_file" 2>/dev/null || true
        error "Failed to write to $filename (disk full? permissions?)"
        return 1
    fi

    # Move temp file to final location with error handling
    if ! mv "$temp_file" "$filename" 2>/dev/null; then
        rm -f "$temp_file" 2>/dev/null || true
        error "Failed to update $filename (permissions? directory missing?)"
        return 1
    fi

    return 0
}

# Cleanup old log files, keeping only the most recent N
# Usage: cleanup_old_logs "log_dir" "pattern" MAX_KEEP
# Example: cleanup_old_logs "logs" "deploy-*.log" 30
cleanup_old_logs() {
    local log_dir="$1"
    local pattern="$2"
    local max_keep="${3:-30}"

    # Count matching files
    local log_count
    log_count=$(ls -1 "$log_dir"/$pattern 2>/dev/null | wc -l || echo "0")

    if [ "$log_count" -gt "$max_keep" ]; then
        log "Cleaning up old logs in $log_dir..."
        # Sort by modification time (newest first), skip first N, delete rest
        # Using ls -t for BSD/macOS compatibility (instead of find -printf)
        ls -1t "$log_dir"/$pattern 2>/dev/null | tail -n +$((max_keep + 1)) | xargs rm -f || true
    fi
}

# Require jq to be installed
# Usage: require_jq
require_jq() {
    if ! command -v jq &> /dev/null; then
        error "jq is required but not installed. Install with: apt-get install jq or brew install jq"
        exit 1
    fi
}

# Require curl to be installed
# Usage: require_curl
require_curl() {
    if ! command -v curl &> /dev/null; then
        error "curl is required but not installed. Install with: apt-get install curl or brew install curl"
        exit 1
    fi
}

# Validate docker-compose.yml exists in project root
# Usage: validate_compose_file
validate_compose_file() {
    if [ ! -f "$PROJECT_DIR/docker-compose.yml" ]; then
        error "docker-compose.yml not found. Not in project root?"
        exit 1
    fi
}

# List available backups
# Usage: list_backups
list_backups() {
    echo "Available backups:"
    dc_run run --rm volman list
}

# Setup emergency restart trap for service recovery
# Usage: setup_emergency_restart
# Call this early in scripts that stop services
setup_emergency_restart() {
    cleanup() {
        local exit_code=$?
        if [ "${SERVICES_STOPPED:-0}" -eq 1 ]; then
            log "Script interrupted! Attempting to restart services..."
            dc_run up -d || true
            log "Emergency restart attempted. Check service status!"
        fi
        exit $exit_code
    }

    trap cleanup EXIT INT TERM
}

# Mark services as stopped (for emergency restart)
# Usage: mark_services_stopped
mark_services_stopped() {
    SERVICES_STOPPED=1
    export SERVICES_STOPPED
}

# Mark services as running (disable emergency restart)
# Usage: mark_services_running
mark_services_running() {
    SERVICES_STOPPED=0
    export SERVICES_STOPPED
}

# Get deployed version from file
# Usage: version=$(get_deployed_version)
get_deployed_version() {
    cat "$VERSION_FILE" 2>/dev/null || echo "unknown"
}

# Get previous version from file
# Usage: version=$(get_previous_version)
get_previous_version() {
    cat "$PREVIOUS_VERSION_FILE" 2>/dev/null || echo ""
}

# Save deployed version to file atomically
# Usage: save_deployed_version "version"
save_deployed_version() {
    local version="$1"
    atomic_write "$VERSION_FILE" "$version"
}

# Save previous version to file atomically
# Usage: save_previous_version "version"
save_previous_version() {
    local version="$1"
    atomic_write "$PREVIOUS_VERSION_FILE" "$version"
}

# Get backup reference from file
# Usage: backup=$(get_backup_reference)
get_backup_reference() {
    cat "$BACKUP_REF_FILE" 2>/dev/null || echo ""
}

# Save backup reference to file atomically
# Usage: save_backup_reference "backup_name"
save_backup_reference() {
    local backup_name="$1"
    atomic_write "$BACKUP_REF_FILE" "$backup_name"
}

# Get current git commit hash
# Usage: get_git_commit
get_git_commit() {
    git rev-parse HEAD 2>/dev/null || echo "unknown"
}

# Get current git branch
# Usage: get_git_branch
get_git_branch() {
    git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown"
}

# Check if running in detached HEAD state
# Usage: if is_detached_head; then ...; fi
is_detached_head() {
    local branch
    branch=$(get_git_branch)
    [ "$branch" = "HEAD" ]
}

# Run git with submodule recursion disabled for this invocation
# Usage: git_no_submodules pull origin master
#
# routy's global git config sets submodule.recurse=true, which makes git pull
# recurse into this repository's submodules. On a clean, fast-forward-only pull
# that touches no submodule pointer, that recursion dies with
#   fatal: bad object 0000000000000000000000000000000000000000
# before anything is updated, so every default (no --tag) deploy is blocked at
# the code-update step. Running the same pull with submodule.recurse=false
# fast-forwards cleanly - the evidence, from routy, is in issue #1406.
#
# -c applies to this invocation only: it does not change the host's config, and
# it keeps working on a host where submodule.recurse was never set.
# Submodules are updated afterwards by update_submodules(), explicitly.
git_no_submodules() {
    git -c submodule.recurse=false "$@"
}

# Bring submodules to the commits the superproject records
# Usage: update_submodules [log_file]
# Always returns 0 - a stale submodule must not abort a deploy
#
# git_no_submodules() takes submodule updates out of the pull, so they have to
# happen here instead. They cannot simply be dropped: docker-compose.yml
# bind-mounts docker/homeassistant/custom_components/sunseeker-lawn-mower into
# the Home Assistant container, so a submodule pointer bump on master has to
# reach the working tree to take effect.
#
# Non-fatal on purpose. By this point the deploy has already fetched its images
# and is about to back up and restart; failing here would abort a deploy over
# submodules that no service needs to be at their newest recorded commit.
update_submodules() {
    local log_file="${1:-${LOG_FILE:-/dev/null}}"

    log "Updating submodules..."
    if ! git submodule update --init --recursive 2>&1 | tee -a "$log_file"; then
        log "WARNING: submodule update failed. Continuing with the submodules already checked out."
    fi
    return 0
}

# Update the working tree to origin/master
# Usage: update_code
# Returns 0 on success, non-zero if the checkout or pull failed
#
# The deploy path's only writer of the working tree. Kept here rather than
# inline in deploy.sh so the submodule handling above has one home and can be
# tested. See issue #1406.
update_code() {
    log "Pulling latest code..."
    git_no_submodules checkout master || return $?
    git_no_submodules pull origin master || return $?
    update_submodules
}

# Format version string for display (truncate long git SHAs)
# Usage: short_version=$(format_version_short "$version")
format_version_short() {
    local version="$1"
    if [ ${#version} -ge 40 ]; then
        # Full git SHA, truncate to 8 chars
        echo "${version:0:8}"
    else
        echo "$version"
    fi
}

# Determine backup name from argument or reference file
# Usage: backup_name=$(determine_backup_name "$backup_name")
# Returns backup name or exits with error if none found
determine_backup_name() {
    local backup_name="${1:-}"

    if [ -z "$backup_name" ]; then
        backup_name=$(get_backup_reference)
    fi

    if [ -z "$backup_name" ]; then
        error "No backup specified and no recent backup found"
        echo ""
        echo "Please specify a backup name or use --list to see available backups." >&2
        echo "" >&2
        list_backups
        return 1
    fi

    echo "$backup_name"
}

# Validate backup name and exit on error
# Usage: validate_backup_or_exit "$backup_name"
validate_backup_or_exit() {
    local backup_name="$1"

    if [ -z "$backup_name" ]; then
        return 0  # Empty name is ok, will be handled elsewhere
    fi

    if ! validate_backup_name "$backup_name"; then
        # validate_backup_name already printed the error
        exit 1
    fi
}

# Check if services are running and exit with error if they are
# Usage: require_services_stopped
# Works with both docker-compose 1.x and 2.x
require_services_stopped() {
    local running_count
    running_count=$(get_running_services_count)

    if [ "$running_count" -gt 0 ]; then
        error "Services are still running. Stop them first:"
        echo "  $DOCKER_COMPOSE_CMD down" >&2
        echo "" >&2
        echo "Or use deploy.sh/rollback.sh which handle this automatically." >&2
        return 1
    fi
    return 0
}

# Determine previous version from saved file or git history
# Usage: prev_version=$(determine_previous_version "$current_version")
determine_previous_version() {
    local current_version="$1"
    local prev_version

    prev_version=$(get_previous_version)

    if [ -z "$prev_version" ]; then
        log "No saved previous version, calculating from git history..."
        if [ "$current_version" != "unknown" ] && [ ${#current_version} -ge 7 ]; then
            prev_version=$(git rev-parse "$current_version^" 2>/dev/null || echo "latest")
        else
            prev_version="latest"
        fi
    else
        log "Using saved previous version"
    fi

    echo "$prev_version"
}

# Checkout specific git version with validation and error handling
# Usage: checkout_git_version "version" [log_file]
# Returns 0 on success, 1 on failure
checkout_git_version() {
    local version="$1"
    local log_file="${2:-${LOG_FILE:-/dev/null}}"

    # Validate git reference
    if ! git rev-parse --verify "${version}^{commit}" >/dev/null 2>&1; then
        error "Invalid git reference: $version"
        return 1
    fi

    log "Checking out version: $version"
    log "WARNING: This will put the repository in detached HEAD state"

    # Non-recursive: submodule.recurse applies to checkout too, and a rollback
    # that fails here degrades to "continuing with current code" - a rollback
    # that silently does not roll the code back. See git_no_submodules(), #1406.
    if ! git_no_submodules checkout "$version" 2>&1 | tee -a "$log_file"; then
        log "WARNING: git checkout failed. Trying with --force..."
        if ! git_no_submodules checkout --force "$version" 2>&1 | tee -a "$log_file"; then
            log "WARNING: Could not checkout version. Continuing with current code."
            return 1
        fi
    fi

    return 0
}

# Export functions and variables for use in scripts
export -f dc_run
export -f supports_json_format
export -f get_running_services_count
export -f get_unhealthy_services
export -f get_starting_services
export -f log
export -f error
export -f confirm
export -f notify
export -f dotenv_value
export -f resolve_secrets_dir
export -f load_notification_secrets
export -f acquire_lock
export -f validate_backup_name
export -f validate_image_tag
export -f services_running
export -f wait_for_health
export -f atomic_write
export -f cleanup_old_logs
export -f require_jq
export -f require_curl
export -f validate_compose_file
export -f list_backups
export -f setup_emergency_restart
export -f mark_services_stopped
export -f mark_services_running
export -f get_deployed_version
export -f get_previous_version
export -f save_deployed_version
export -f save_previous_version
export -f get_backup_reference
export -f save_backup_reference
export -f backup_mongo
export -f get_git_commit
export -f get_git_branch
export -f is_detached_head
export -f git_no_submodules
export -f update_submodules
export -f update_code
export -f format_version_short
export -f determine_backup_name
export -f validate_backup_or_exit
export -f require_services_stopped
export -f determine_previous_version
export -f checkout_git_version
export -f warn
export -f require_compose_v2
export -f compose_base_files
export -f dc_base
export -f dc_deploy
export -f long_running_services
export -f stateful_services
export -f persistent_mounts
export -f compose_state_volumes
export -f service_config_files_hash
export -f _hash_host_path
export -f _hash_host_path_uncached
export -f image_repo_digest
export -f generate_deploy_override
export -f predict_recreate
export -f container_states
export -f stack_run_state
export -f changed_services
export -f image_changed_services
export -f _gate_now
export -f _gate_sleep
export -f health_gate

export DOCKER_COMPOSE_CMD
export SCRIPT_DIR
export PROJECT_DIR
export LOCK_FILE
export VERSION_FILE
export PREVIOUS_VERSION_FILE
export BACKUP_REF_FILE
export SNAPSHOT_REF_FILE
export DEPLOY_OVERRIDE_FILE
export CONFIG_HASH_LABEL
export STATEFUL_LABEL
export HEALTH_STABLE_SECONDS
export HEALTH_POLL_INTERVAL
export HEALTH_GATE_MARGIN
# shellcheck disable=SC2090
export _GATE_JQ
export SERVICES_STOPPED
