apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    version: 1
    editable: false
    isDefault: true
    access: proxy
    url: $INFLUXDB_URL
    jsonData:
      httpMode: GET
    database: $INFLUXDB_DATABASE
    user: $INFLUXDB_USER
    secureJsonData:
      password: $INFLUXDB_USER_PASSWORD
