# Sample docker-compose service configuration for automation status monitoring
# This service should be added to the main docker-compose.yml file

version: '3.8'

services:
  mqtt-influx-automation-status:
    build: docker/mqtt-influx
    environment:
      # MQTT Configuration
      - BROKER=mqtt://broker
      - TOPIC=homy/automation/+/status
      - MQTT_CLIENT_ID=mqtt-influx-automation-status

      # InfluxDB Configuration
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_DATABASE=homy
      - INFLUXDB_USERNAME=writer
      - INFLUXDB_PASSWORD_FILE=/run/secrets/influxdb_write_user_password

      # Service Tags
      - TAGS={"source":"automation_status_bridge"}

    secrets:
      - influxdb_write_user_password

    depends_on:
      - broker
      - influxdb

    restart: unless-stopped

    # Health check to ensure service is processing messages
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Service running')"]
      interval: 30s
      timeout: 10s
      retries: 3

    labels:
      - "traefik.enable=false"  # Not a web service

secrets:
  influxdb_write_user_password:
    file: ./secrets/influxdb_write_user_password

# Expected MQTT message format:
# Topic: homy/automation/boiler_controller/status
# Payload: {
#   "_type": "automation-status",
#   "reason": "comfort_heating_top_45.2C",
#   "controlMode": "automatic",
#   "manualOverrideExpires": null,
#   "heaterState": true,
#   "solarCirculation": false,
#   "temperatures": {
#     "top": 45.2,
#     "bottom": 42.8,
#     "solar": 38.1,
#     "ambient": 26.9
#   },
#   "_bot": {
#     "name": "boiler_controller",
#     "type": "boiler-controller"
#   },
#   "_tz": 1726325400000
# }