apiVersion: 1

groups:
  - orgId: 1
    name: AC alert webhook
    folder: Webhook Alerting
    interval: 1m
    rules:
      - uid: webhook-3057STtVkz
        title: AC alert (Webhook)
        condition: A
        data:
          - refId: maxV
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              alias: "max V"
              groupBy:
                - params: ["$__interval"]
                  type: time
                - params: ["null"]
                  type: fill
              intervalMs: 1000
              maxDataPoints: 43200
              measurement: current_power
              orderByTime: ASC
              policy: default
              resultFormat: time_series
              select:
                - - params: ["v"]
                    type: field
                  - params: []
                    type: max
              tags:
                # Exclude kitchen meter - faulty device that occasionally returns 0V readings
                - key: "device.name"
                  operator: "!="
                  value: kitchen
          - refId: minV
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              alias: "min V"
              groupBy:
                - params: ["$__interval"]
                  type: time
                - params: ["null"]
                  type: fill
              intervalMs: 1000
              maxDataPoints: 43200
              measurement: current_power
              orderByTime: ASC
              policy: default
              resultFormat: time_series
              select:
                - - params: ["v"]
                    type: field
                  - params: []
                    type: min
              tags:
                # Exclude kitchen meter - faulty device that occasionally returns 0V readings
                - key: "device.name"
                  operator: "!="
                  value: kitchen
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              conditions:
                - evaluator:
                    params: [210]
                    type: lt
                  operator:
                    type: and
                  query:
                    params: [minV]
                  reducer:
                    type: min
                - evaluator:
                    params: [248]
                    type: gt
                  operator:
                    type: or
                  query:
                    params: [maxV]
                  reducer:
                    type: max
              intervalMs: 1000
              maxDataPoints: 43200
              type: classic_conditions
        noDataState: OK
        execErrState: OK
        for: 0s
        annotations:
          __alertId__: "12"
          __dashboardUid__: "Nml0-Fonz"
          __panelId__: "3"
          summary: "⚡ AC voltage out of range"
          description: "The AC voltage has gone outside the safe operating range of 210-247V. This could indicate power quality issues or electrical problems."
        labels:
          rule_uid: webhook-3057STtVkz
          alert_type: webhook
