apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram-webhook
    receivers:
      - uid: telegram-webhook
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://telegram-bridge:3000/webhook
          httpMethod: POST
          maxAlerts: 0
          title: "Home Automation Alert"