apiVersion: 1

groups:
  - orgId: 1
    name: Пералня webhook
    folder: Webhook Alerting
    interval: 5m
    rules:
      - uid: webhook-XA5nIopVk
        title: Пералня (Webhook)
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 1800
              to: 300
            datasourceUid: P3C6603E967DC8568
            model:
              groupBy:
                - params: ["$__interval"]
                  type: time
                - params: ["null"]
                  type: fill
              intervalMs: 1000
              maxDataPoints: 43200
              measurement: current_power
              orderByTime: ASC
              policy: default
              resultFormat: time_series
              select:
                - - params: ["p"]
                    type: field
                  - params: []
                    type: max
              tags:
                - key: "device.name"
                  operator: "="
                  value: laundry
          - refId: B
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              groupBy:
                - params: ["$__interval"]
                  type: time
                - params: ["null"]
                  type: fill
              intervalMs: 1000
              maxDataPoints: 43200
              measurement: current_power
              orderByTime: ASC
              policy: default
              resultFormat: time_series
              select:
                - - params: ["p"]
                    type: field
                  - params: []
                    type: max
              tags:
                - key: "device.name"
                  operator: "="
                  value: laundry
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              conditions:
                - evaluator:
                    params: [2]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    type: max
                - evaluator:
                    params: [2]
                    type: lt
                  operator:
                    type: and
                  query:
                    params: [B]
                  reducer:
                    type: max
              intervalMs: 1000
              maxDataPoints: 43200
              type: classic_conditions
        noDataState: NoData
        execErrState: OK
        for: 0s
        annotations:
          __alertId__: "1"
          __dashboardUid__: "reminders"
          __panelId__: "2"
          message: "👕 Известие за пералнята: Пералнята е готова"
          summary: "Напомняне за пералня"
          description: "Пералнята завърши цикъла си - консумацията спадна под 2W. Можете да изважите дрехите."
        labels:
          rule_uid: webhook-XA5nIopVk
          alert_type: webhook