apiVersion: 1

groups:
  - orgId: 1
    name: Sunseeker Lawn Mower Alerts
    folder: Lawn Mower
    interval: 30s
    rules:
      - uid: sunseeker-battery-low
        title: Sunseeker Battery Low
        condition: A
        data:
          - refId: battery
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              measurement: sunseeker_power
              select:
                - - params: ["value"]
                    type: field
                  - params: []
                    type: last
              resultFormat: time_series
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 15
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - battery
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: battery
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          description: "Sunseeker lawn mower battery is critically low at {{ $values.battery.Value }}%"
          runbook_url: ""
          summary: "Battery level is below 15%"
        labels:
          severity: critical
          device: sunseeker
          type: battery
          
      - uid: sunseeker-battery-temp-high
        title: Sunseeker Battery Temperature High
        condition: A
        data:
          - refId: temperature
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              measurement: sunseeker_battery_detail
              select:
                - - params: ["temperature"]
                    type: field
                  - params: []
                    type: last
              resultFormat: time_series
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 45
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - temperature
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: temperature
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: "Sunseeker battery temperature is dangerously high at {{ $values.temperature.Value }}°C"
          runbook_url: ""
          summary: "Battery temperature exceeds safe operating limits"
        labels:
          severity: warning
          device: sunseeker
          type: temperature
          
      - uid: sunseeker-connection-lost
        title: Sunseeker Connection Lost
        condition: A
        data:
          - refId: connection
            queryType: ''
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              measurement: sunseeker_connection
              select:
                - - params: ["connected"]
                    type: field
                  - params: []
                    type: last
              resultFormat: time_series
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - connection
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: connection
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
              type: threshold
        noDataState: Alerting
        execErrState: Alerting
        for: 3m
        annotations:
          description: "Lost connection to Sunseeker lawn mower"
          runbook_url: ""
          summary: "Mower is not responding to communication"
        labels:
          severity: warning
          device: sunseeker
          type: connectivity
          
      - uid: sunseeker-battery-voltage-low
        title: Sunseeker Battery Voltage Critical
        condition: A
        data:
          - refId: voltage
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              measurement: sunseeker_battery_detail
              select:
                - - params: ["voltage"]
                    type: field
                  - params: []
                    type: last
              resultFormat: time_series
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 20
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - voltage
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: voltage
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: "Sunseeker battery voltage critically low at {{ $values.voltage.Value }}V"
          runbook_url: ""
          summary: "Battery voltage below safe operating threshold"
        labels:
          severity: critical
          device: sunseeker
          type: battery
          
      - uid: sunseeker-tilt-warning
        title: Sunseeker Excessive Tilt
        condition: A
        data:
          - refId: pitch
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              measurement: sunseeker_battery_detail
              select:
                - - params: ["pitch"]
                    type: field
                  - params: []
                    type: max
              resultFormat: time_series
          - refId: roll
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              measurement: sunseeker_battery_detail
              select:
                - - params: ["roll"]
                    type: field
                  - params: []
                    type: max
              resultFormat: time_series
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 25
                    type: gt
                  operator:
                    type: or
                  query:
                    params:
                      - pitch
                  reducer:
                    params: []
                    type: last
                  type: query
                - evaluator:
                    params:
                      - 25
                    type: gt
                  operator:
                    type: or
                  query:
                    params:
                      - roll
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: max(pitch, roll)
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 30s
        annotations:
          description: "Sunseeker is tilted at dangerous angle - Pitch: {{ $values.pitch.Value }}°, Roll: {{ $values.roll.Value }}°"
          runbook_url: ""
          summary: "Mower tilt exceeds safe operating limits"
        labels:
          severity: warning
          device: sunseeker
          type: navigation
          
      - uid: sunseeker-stuck-alert
        title: Sunseeker Appears Stuck
        condition: A
        data:
          - refId: mode
            queryType: ''
            relativeTimeRange:
              from: 1800
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              measurement: sunseeker_mode
              select:
                - - params: ["value"]
                    type: field
                  - params: []
                    type: last
              resultFormat: time_series
          - refId: heading_changes
            queryType: ''
            relativeTimeRange:
              from: 1800
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              measurement: sunseeker_battery_detail
              select:
                - - params: ["heading"]
                    type: field
                  - params: []
                    type: stddev
              resultFormat: time_series
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: eq
                  operator:
                    type: and
                  query:
                    params:
                      - mode
                  reducer:
                    params: []
                    type: last
                  type: query
                - evaluator:
                    params:
                      - 5
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - heading_changes
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: mode == 1 AND heading_changes < 5
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 15m
        annotations:
          description: "Sunseeker has been in mowing mode but shows minimal movement for extended period"
          runbook_url: ""
          summary: "Mower may be stuck or blocked"
        labels:
          severity: warning
          device: sunseeker
          type: operation