apiVersion: 1

groups:
  - orgId: 1
    name: Sunseeker Battery Alerts
    folder: Lawn Mower
    interval: 5m
    rules:
      - uid: sunseeker-battery-low
        title: Sunseeker Battery Low
        condition: A
        data:
          - refId: battery
            queryType: ''
            relativeTimeRange:
              from: 14400
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              query: 'SELECT last("battery_percentage") FROM "sunseeker_power" WHERE time >= now() - 4h'
              rawQuery: true
              resultFormat: time_series
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 15
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - battery
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: battery
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
              type: classic_conditions
        noDataState: NoData
        execErrState: Alerting
        for: 10m
        annotations:
          description: "Sunseeker lawn mower battery is critically low at {{ $values.battery.Value }}%"
          runbook_url: ""
          summary: "Battery level is below 15%"
        labels:
          severity: critical
          device: sunseeker
          type: battery
          
      - uid: sunseeker-battery-voltage-low
        title: Sunseeker Battery Voltage Critical
        condition: A
        data:
          - refId: voltage
            queryType: ''
            relativeTimeRange:
              from: 14400
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              query: 'SELECT last("voltage") FROM "sunseeker_battery_detail" WHERE time >= now() - 4h'
              rawQuery: true
              resultFormat: time_series
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 18
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - voltage
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: voltage
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
              type: classic_conditions
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: "Sunseeker battery voltage critically low at {{ $values.voltage.Value }}mV"
          runbook_url: ""
          summary: "Battery voltage below safe operating threshold"
        labels:
          severity: critical
          device: sunseeker
          type: battery