apiVersion: 1

groups:
  - orgId: 1
    name: Sunseeker Operation Alerts
    folder: Lawn Mower
    interval: 30s
    rules:
      - uid: sunseeker-tilt-warning
        title: Sunseeker Excessive Tilt
        condition: A
        data:
          - refId: pitch
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              measurement: sunseeker_battery_detail
              select:
                - - params: ["pitch"]
                    type: field
                  - params: []
                    type: last
              resultFormat: time_series
          - refId: roll
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              measurement: sunseeker_battery_detail
              select:
                - - params: ["roll"]
                    type: field
                  - params: []
                    type: last
              resultFormat: time_series
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 25
                      - 25
                    type: outside_range
                  operator:
                    type: or
                  query:
                    params:
                      - pitch
                  reducer:
                    params: []
                    type: last
                  type: query
                - evaluator:
                    params:
                      - 25
                      - 25
                    type: outside_range
                  operator:
                    type: or
                  query:
                    params:
                      - roll
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: abs(pitch) > 25 OR abs(roll) > 25
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 30s
        annotations:
          description: "Sunseeker is tilted at dangerous angle - Pitch: {{ $values.pitch.Value }}°, Roll: {{ $values.roll.Value }}°"
          runbook_url: ""
          summary: "Mower tilt exceeds safe operating limits"
        labels:
          severity: warning
          device: sunseeker
          type: navigation
          
      - uid: sunseeker-stuck-alert
        title: Sunseeker Appears Stuck
        condition: A
        data:
          - refId: mode
            queryType: ''
            relativeTimeRange:
              from: 1800
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              measurement: sunseeker_mode
              select:
                - - params: ["mode"]
                    type: field
                  - params: []
                    type: last
              resultFormat: time_series
          - refId: heading_changes
            queryType: ''
            relativeTimeRange:
              from: 1800
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              measurement: sunseeker_battery_detail
              select:
                - - params: ["heading"]
                    type: field
                  - params: []
                    type: stddev
              resultFormat: time_series
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: eq
                  operator:
                    type: and
                  query:
                    params:
                      - mode
                  reducer:
                    params: []
                    type: last
                  type: query
                - evaluator:
                    params:
                      - 5
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - heading_changes
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: mode == 1 AND heading_changes < 5
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 15m
        annotations:
          description: "Sunseeker has been in mowing mode but shows minimal movement for extended period"
          runbook_url: ""
          summary: "Mower may be stuck or blocked"
        labels:
          severity: warning
          device: sunseeker
          type: operation