apiVersion: 1

groups:
  - orgId: 1
    name: Water pump power alert webhook
    folder: Webhook Alerting
    interval: 1m
    rules:
      - uid: webhook-z157Sot4z
        title: Water pump power alert (Webhook)
        condition: B
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 900
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              groupBy:
                - params: ["$__interval"]
                  type: time
                - params: ["null"]
                  type: fill
              interval: 13m
              intervalMs: 1000
              maxDataPoints: 43200
              measurement: current_power
              orderByTime: ASC
              policy: default
              resultFormat: time_series
              select:
                - - params: ["p"]
                    type: field
                  - params: []
                    type: mean
              tags:
                - key: "device.name"
                  operator: "="
                  value: water_pump
          - refId: B
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              conditions:
                - evaluator:
                    params: [1000]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    type: avg
              intervalMs: 1000
              maxDataPoints: 43200
              type: classic_conditions
        noDataState: NoData
        execErrState: OK
        for: 15m
        annotations:
          __alertId__: "16"
          __dashboardUid__: "VXUnb8gVk"
          __panelId__: "2"
          message: "Претоварване на сондажната помпа"
        labels:
          rule_uid: webhook-z157Sot4z
          alert_type: webhook